<a href="https://colab.research.google.com/github/mini1115/TIL/blob/master/%EB%B9%85%EB%B6%84%EA%B8%B0/Data_Manim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data=pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv',sep='\t')

In [ ]:
data.head(5)

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18

In [ ]:
data.shape
print("행:",data.shape[0])
print("열:",data.shape[1])

행: 51490
열: 61

In [ ]:
print(data.columns)

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHeraldKills', 't2_ban1', 't2_ban2', 't2_ban3', 't2_ban4',
       't2_ban5'],
      dtype='object')

In [ ]:
ans = data.columns
ans[5]

'firstBlood'

In [ ]:
ans = data.iloc[:,5].dtype
print(ans)

int64

In [ ]:
print(data.index)

RangeIndex(start=0, stop=51490, step=1)

In [ ]:
ans = data.iloc[2,5]
print(ans)

2

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv',encoding='euc-kr')
df.tail(3)

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.0
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.5
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.8

In [ ]:
ans = df.select_dtypes(exclude='O')
print(ans.columns)

Index(['id', '거주인구', '근무인구', '방문인구', '총 유동인구', '평균 속도', '평균 소요 시간', '평균 기온',
       '일강수량', '평균 풍속'],
      dtype='object')

In [ ]:
ans = df.select_dtypes(include='O')
print(ans.columns)

Index(['일자', '시도명', '읍면동명'], dtype='object')

In [ ]:
ans = df.isnull().sum()
print(ans)

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB
None

In [ ]:
ans = df.select_dtypes(exclude='O')
ans.describe()

,id,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
count,9621.000000,9.621000e+03,9621.000000,9621.000000,9.621000e+03,9621.000000,9621.000000,9621.000000,9621.000000,9621.000000
mean,27258.000000,3.174315e+05,35471.201510,195889.561802,5.487922e+05,41.109084,37.215873,13.550828,6.972426,2.753171
std,2777.487804,2.982079e+05,40381.214775,140706.090325,4.608802e+05,8.758631,12.993786,7.745515,27.617260,1.498538
min,22448.000000,9.305552e+03,1407.936000,11538.322000,2.225181e+04,24.333000,12.667000,-9.600000,0.000000,0.000000
25%,24853.000000,9.539939e+04,12074.498000,99632.153000,2.216910e+05,34.250000,27.889000,7.600000,0.000000,1.700000
50%,27258.000000,2.221105e+05,21960.928000,152805.335000,3.866935e+05,39.640000,34.500000,13.400000,0.000000,2.400000
75%,29663.000000,4.106671e+05,40192.032000,236325.109000,6.406918e+05,49.105000,46.176000,19.700000,1.500000,3.400000
max,32068.000000,1.364504e+06,263476.965000,723459.209000,2.066484e+06,103.000000,172.200000,30.400000,587.500000,13.333000

In [ ]:
print(df['거주인구'])

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: 거주인구, Length: 9621, dtype: float64

In [ ]:
print(df['평균 속도'].quantile(0.75)-df['평균 속도'].quantile(0.25))

14.854999999999997

In [ ]:
print(df['읍면동명'].nunique())

41

In [ ]:
print(df['읍면동명'].unique())

['도두동' '외도동' '이도2동' '일도1동' '대천동' '서홍동' '한경면' '송산동' '조천읍' '일도2동' '영천동'
 '예래동' '대륜동' '삼도1동' '이호동' '건입동' '중앙동' '삼양동' '삼도2동' '이도1동' '남원읍' '대정읍'
 '정방동' '효돈동' '아라동' '한림읍' '구좌읍' '용담1동' '오라동' '화북동' '연동' '표선면' '중문동' '성산읍'
 '안덕면' '천지동' '노형동' '동홍동' '용담2동' '봉개동' '애월읍']

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
ans = df.loc[df['quantity']==3].head()
print(ans)

   order_id  quantity                              item_name  \
0         1         3           Chips and Fresh Tomato Salsa
1         1         3                                   Izze
2         1         3                       Nantucket Nectar
3         1         3  Chips and Tomatillo-Green Chili Salsa
4         2         3                           Chicken Bowl

                                  choice_description item_price   ans
0                                                NaN     $2.39   True
1                                       [Clementine]     $3.39   True
2                                            [Apple]     $3.39   True
3                                                NaN     $2.39   True
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   True

In [ ]:
ans = df.loc[df['quantity']==3].head().reset_index(drop=True)
print(ans)

   order_id  quantity                              item_name  \
0         1         3           Chips and Fresh Tomato Salsa
1         1         3                                   Izze
2         1         3                       Nantucket Nectar
3         1         3  Chips and Tomatillo-Green Chili Salsa
4         2         3                           Chicken Bowl

                                  choice_description item_price   ans
0                                                NaN     $2.39   True
1                                       [Clementine]     $3.39   True
2                                            [Apple]     $3.39   True
3                                                NaN     $2.39   True
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   True

In [ ]:
ans = df.loc[df['quantity']==3].head().reset_index(drop=False)
print(ans)

   index  order_id  quantity                              item_name  \
0      0         1         3           Chips and Fresh Tomato Salsa
1      1         1         3                                   Izze
2      2         1         3                       Nantucket Nectar
3      3         1         3  Chips and Tomatillo-Green Chili Salsa
4      4         2         3                           Chicken Bowl

                                  choice_description item_price   ans
0                                                NaN     $2.39   True
1                                       [Clementine]     $3.39   True
2                                            [Apple]     $3.39   True
3                                                NaN     $2.39   True
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   True

In [ ]:
ans = df[['quantity', 'item_price']]
print(ans)

      quantity item_price
0            1     $2.39
1            1     $3.39
2            1     $3.39
3            1     $2.39
4            2    $16.98
...        ...        ...
4617         1    $11.75
4618         1    $11.75
4619         1    $11.25
4620         1     $8.75
4621         1     $8.75

[4622 rows x 2 columns]

item_price 컬럼의 달러표시 문자를 제거하고 float 타입으로 저장하여 new_price 컬럼에 저장하라

In [ ]:
df['new_price'] = df['item_price'].str[1:].astype('float')
df['new_price']

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: new_price, Length: 4622, dtype: float64

new_price 컬럼이 5이하의 값을 가지는 데이터프레임을 추출하고, 전체 갯수를 구하여라

In [ ]:
ans = len(df.loc[df['new_price']<=5])
ans

1652

item_name명이 Chicken Salad Bowl 인 데이터 프레임을 추출하라고 index 값을 초기화 하여라

In [ ]:
df[df['item_name']=='Chicken Bowl'].reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
1,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
2,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25
3,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75,8.75
4,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49,8.49
...,...,...,...,...,...,...
721,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25,11.25
722,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75,8.75
723,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75,8.75
724,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75,8.75
725,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75

new_price값이 9 이하이고 item_name 값이 Chicken Salad Bowl 인 데이터 프레임을 추출하라

In [ ]:
ans = df.loc[(df['new_price'] <=9) & (df['item_name']=='Chicken Salad Bowl')]
print(ans)

      order_id  quantity           item_name  \
44          20         1  Chicken Salad Bowl
256        111         1  Chicken Salad Bowl
526        220         1  Chicken Salad Bowl
528        221         1  Chicken Salad Bowl
529        221         1  Chicken Salad Bowl
568        234         1  Chicken Salad Bowl
585        240         1  Chicken Salad Bowl
693        286         1  Chicken Salad Bowl
702        289         1  Chicken Salad Bowl
762        314         1  Chicken Salad Bowl
1109       458         1  Chicken Salad Bowl
1460       592         1  Chicken Salad Bowl
1471       598         1  Chicken Salad Bowl
1483       602         1  Chicken Salad Bowl
1547       628         1  Chicken Salad Bowl
1601       649         1  Chicken Salad Bowl
1621       654         1  Chicken Salad Bowl
1756       709         1  Chicken Salad Bowl
1977       798         1  Chicken Salad Bowl
2031       818         1  Chicken Salad Bowl
2113       850         1  Chicken Salad Bowl
2224       896         1  Chicken Salad Bowl
2314       926         1  Chicken Salad Bowl
2728      1083         1  Chicken Salad Bowl
2858      1136         1  Chicken Salad Bowl
2883      1145         1  Chicken Salad Bowl
2897      1152         1  Chicken Salad Bowl
2989      1189         1  Chicken Salad Bowl
3033      1206         1  Chicken Salad Bowl
3069      1222         1  Chicken Salad Bowl
3117      1243         1  Chicken Salad Bowl
3259      1305         1  Chicken Salad Bowl
3261      1305         1  Chicken Salad Bowl
3310      1327         1  Chicken Salad Bowl
3315      1329         1  Chicken Salad Bowl
3381      1357         1  Chicken Salad Bowl
3411      1368         1  Chicken Salad Bowl
3623      1450         1  Chicken Salad Bowl
3656      1461         1  Chicken Salad Bowl
3706      1483         1  Chicken Salad Bowl
3712      1483         1  Chicken Salad Bowl
3790      1517         1  Chicken Salad Bowl
3798      1521         1  Chicken Salad Bowl
3974      1592         1  Chicken Salad Bowl
3997      1601         1  Chicken Salad Bowl
4012      1606         1  Chicken Salad Bowl
4035      1615         1  Chicken Salad Bowl
4064      1627         1  Chicken Salad Bowl
4205      1679         1  Chicken Salad Bowl
4207      1679         1  Chicken Salad Bowl
4333      1730         1  Chicken Salad Bowl
4352      1738         1  Chicken Salad Bowl
4439      1769         1  Chicken Salad Bowl
4520      1797         1  Chicken Salad Bowl
4620      1834         1  Chicken Salad Bowl
4621      1834         1  Chicken Salad Bowl

                                     choice_description item_price  new_price
44    [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75        8.75
256   [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $8.75        8.75
526   [Roasted Chili Corn Salsa, [Black Beans, Sour ...     $8.75        8.75
528   [Tomatillo Green Chili Salsa, [Fajita Vegetabl...     $8.75        8.75
529   [Tomatillo Green Chili Salsa, [Fajita Vegetabl...     $8.75        8.75
568             [Fresh Tomato Salsa, Fajita Vegetables]     $8.75        8.75
585             [Fresh Tomato Salsa, Fajita Vegetables]     $8.75        8.75
693   [Fresh Tomato Salsa, [Sour Cream, Cheese, Lett...     $8.75        8.75
702   [Tomatillo Red Chili Salsa, [Black Beans, Chee...     $8.75        8.75
762   [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75        8.75
1109  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $8.75        8.75
1460                      [Fresh Tomato Salsa, Lettuce]     $8.75        8.75
1471  [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75        8.75
1483  [Fresh Tomato Salsa, [Fajita Vegetables, Chees...     $8.75        8.75
1547  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $8.75        8.75
1601  [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75        8.75
1621  [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75        8.75
1756  [Fresh Tomato Salsa, [Fajita Vegetables, Sour ...     $8.75        8.75
1977  [Fresh Tomato Salsa, [Fajita Vegetables, Sour ...     $8.75        8.75
2031  [Roasted Chili Corn Salsa, [Rice, Black Beans,...     $8.75        8.75
2113  [Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]     $8.75        8.75
2224  [Fresh Tomato Salsa, [Pinto Beans, Sour Cream,...     $8.75        8.75
2314     [Roasted Chili Corn Salsa, [Rice, Sour Cream]]     $8.75        8.75
2728      [Roasted Chili Corn Salsa, [Cheese, Lettuce]]     $8.75        8.75
2858  [Fresh Tomato Salsa, [Fajita Vegetables, Chees...     $8.75        8.75
2883  [Roasted Chili Corn Salsa, [Black Beans, Sour ...     $8.75        8.75
2897                 [Roasted Chili Corn Salsa, Cheese]     $8.75        8.75
2989  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $8.75        8.75
3033            [Fresh Tomato Salsa, [Cheese, Lettuce]]     $8.75        8.75
3069  [Fresh Tomato Salsa, [Fajita Vegetables, Black...     $8.75        8.75
3117  [Roasted Chili Corn Salsa, [Rice, Pinto Beans,...     $8.75        8.75
3259  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75        8.75
3261  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75        8.75
3310                               [Fresh Tomato Salsa]     $8.75        8.75
3315              [Fresh Tomato Salsa, [Rice, Lettuce]]     $8.75        8.75
3381            [Fresh Tomato Salsa, [Cheese, Lettuce]]     $8.75        8.75
3411       [Fresh Tomato Salsa, [Pinto Beans, Lettuce]]     $8.75        8.75
3623  [Roasted Chili Corn Salsa, [Rice, Pinto Beans,...     $8.75        8.75
3656  [Tomatillo Green Chili Salsa, [Fajita Vegetabl...     $8.75        8.75
3706  [Roasted Chili Corn Salsa, [Pinto Beans, Chees...     $8.75        8.75
3712  [Roasted Chili Corn Salsa, [Black Beans, Chees...     $8.75        8.75
3790  [Fresh Tomato Salsa, [Fajita Vegetables, Chees...     $8.75        8.75
3798  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75        8.75
3974  [Fresh Tomato Salsa, [Rice, Pinto Beans, Lettu...     $8.75        8.75
3997  [Tomatillo Green Chili Salsa, [Fajita Vegetabl...     $8.75        8.75
4012                               [Fresh Tomato Salsa]     $8.75        8.75
4035  [Fresh Tomato Salsa, [Fajita Vegetables, Chees...     $8.75        8.75
4064  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...     $8.75        8.75
4205  [Roasted Chili Corn Salsa, [Black Beans, Chees...     $8.75        8.75
4207  [Fresh Tomato Salsa, [Black Beans, Cheese, Sou...     $8.75        8.75
4333        [Tomatillo Red Chili Salsa, [Rice, Cheese]]     $8.75        8.75
4352  [Tomatillo Red Chili Salsa, [Rice, Fajita Vege...     $8.75        8.75
4439  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...     $8.75        8.75
4520                      [Fresh Tomato Salsa, Lettuce]     $8.75        8.75
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75        8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75        8.75

df의 item_name 컬럼 값중 Chips 포함하는 경우의 데이터를 출력하라

In [ ]:
ans = df.loc[df['item_name'].str.contains('Chips')]
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
6,3,1,Side of Chips,NaN,$1.69,1.69
10,5,1,Chips and Guacamole,NaN,$4.45,4.45
14,7,1,Chips and Guacamole,NaN,$4.45,4.45
...,...,...,...,...,...,...
4596,1826,1,Chips and Guacamole,NaN,$4.45,4.45
4600,1827,1,Chips and Guacamole,NaN,$4.45,4.45
4605,1828,1,Chips and Guacamole,NaN,$4.45,4.45
4613,1831,1,Chips,NaN,$2.15,2.15
4616,1832,1,Chips and Guacamole,NaN,$4.45,4.45

df의 짝수번째 컬럼만을 포함하는 데이터프레임을 출력하라

In [ ]:
ans = df.iloc[:,::2]
ans

      order_id                              item_name item_price
0            1           Chips and Fresh Tomato Salsa     $2.39
1            1                                   Izze     $3.39
2            1                       Nantucket Nectar     $3.39
3            1  Chips and Tomatillo-Green Chili Salsa     $2.39
4            2                           Chicken Bowl    $16.98
...        ...                                    ...        ...
4617      1833                          Steak Burrito    $11.75
4618      1833                          Steak Burrito    $11.75
4619      1834                     Chicken Salad Bowl    $11.25
4620      1834                     Chicken Salad Bowl     $8.75
4621      1834                     Chicken Salad Bowl     $8.75

[4622 rows x 3 columns]

df의 new_price 컬럼 값에 따라 내림차순으로 정리하고 index를 초기화 하여라

In [ ]:
ans = df.sort_values('new_price',ascending=False).reset_index(drop=True)
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25
1,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
2,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
3,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
4,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
...,...,...,...,...,...,...
4617,1578,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
4618,1162,1,Bottled Water,NaN,$1.09,1.09
4619,567,1,Canned Soda,[Coca Cola],$1.09,1.09
4620,1014,1,Canned Soda,[Coca Cola],$1.09,1.09
4621,591,1,Canned Soda,[Sprite],$1.09,1.09

df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 인덱싱하라

In [ ]:
ans =df.loc[(df['item_name']=='Steak Salad') | (df['item_name']=='Bowl')]
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
752,311,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
893,369,1,Steak Salad,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$8.99,8.99
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후, item_name를 기준으로 중복행이 있으면 제거하되 첫번째 케이스만 남겨라

In [ ]:
ans = df.loc[(df['item_name']=='Steak Salad') | (df['item_name']=='Bowl')]
ans.drop_duplicates('item_name')
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
752,311,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
893,369,1,Steak Salad,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$8.99,8.99
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후, item_name를 기준으로 중복행이 있으면 제거하되 마지막 케이스만 남겨라

In [ ]:
ans = df.loc[(df['item_name']=='Steak Salad') | (df['item_name']=='Bowl')]
ans.drop_duplicates('item_name',keep='last')
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
752,311,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
893,369,1,Steak Salad,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$8.99,8.99
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

df의 데이터 중 new_price값이 new_price값의 평균값 이상을 가지는 데이터들을 인덱싱하라

In [ ]:
ans = df.loc[df['new_price']>=df['new_price'].mean()]
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

df의 데이터 중 item_name의 값이 Izze 데이터를 Fizzy Lizzy로 수정하라

In [ ]:
df.loc[df['item_name']=='Izze','item_name']='Fizzy Lizzy'
df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,Fizzy Lizzy,Fizzy Lizzy,Fizzy Lizzy,Fizzy Lizzy,Fizzy Lizzy,Fizzy Lizzy
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

df의 데이터 중 choice_description 값이 NaN 인 데이터의 갯수를 구하여라

In [ ]:
df['choice_description'].isnull().sum()

1246

df의 데이터 중 choice_description 값이 NaN 인 데이터를 NoData 값으로 대체하라(loc 이용)

In [ ]:
df.loc[df['choice_description'].isnull(),'choice_description']='NoData'
df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
1,Fizzy Lizzy,Fizzy Lizzy,Fizzy Lizzy,Fizzy Lizzy,Fizzy Lizzy,Fizzy Lizzy
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

df의 데이터 중 choice_description 값에 Black이 들어가는 경우를 인덱싱하라

In [ ]:
ans = df.loc[df['choice_description'].str.contains('Black')]
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
...,...,...,...,...,...,...
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25,11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25,9.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75

df의 데이터 중 choice_description 값에 Vegetables 들어가지 않는 경우의 갯수를 출력하라

In [ ]:
ans = len(df.loc[~df['choice_description'].str.contains('Vegetables')])
ans

3900

df의 데이터 중 item_name 값이 N으로 시작하는 데이터를 모두 추출하라

In [ ]:
ans = df.loc[df['item_name'].str.startswith('N')]
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
173,77,1,Nantucket Nectar,[Apple],$3.39,3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78,6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39,3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78,6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39,3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39,3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39,3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39,3.39

df의 데이터 중 item_name 값의 단어갯수가 15개 이상인 데이터를 인덱싱하라

In [ ]:
ans = df[df['item_name'].str.len()>=15]
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
10,5,1,Chips and Guacamole,NoData,$4.45,4.45
...,...,...,...,...,...,...
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75,8.75
4616,1832,1,Chips and Guacamole,NoData,$4.45,4.45
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

df의 데이터 중 new_price값이 lst에 해당하는 경우의 데이터 프레임을 구하고 그 갯수를 출력하라 lst =[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]

In [ ]:
lst =[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]
ans = df.loc[df['new_price'].isin(lst)]
len(ans)

1373

In [28]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv')
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

데이터의 각 host_name의 빈도수를 구하고 host_name으로 정렬하여 상위 5개를 출력하라

In [11]:
df['host_name'].value_counts().sort_values(ascending=False)

host_name
Michael             417
David               403
Sonder (NYC)        327
John                294
Alex                279
                   ...
Martin & Soledad      1
Soheil                1
Keno                  1
Keagon                1
Ilgar & Aysel         1
Name: count, Length: 11452, dtype: int64

In [ ]:
ans = df.value_counts('host_name').sort_index()
ans.head(5)

host_name
'Cil                        1
(Ari) HENRY LEE             1
(Email hidden by Airbnb)    6
(Mary) Haiy                 1
-TheQueensCornerLot         1
Name: count, dtype: int64

데이터의 각 host_name의 빈도수를 구하고 빈도수 기준 내림차순 정렬한 데이터 프레임을 만들어라. 빈도수 컬럼은 counts로 명명하라

In [32]:
ans = df.host_name.value_counts().to_frame().rename(columns={'host_name':'counts'})
ans = ans.sort_values('counts', ascending=False)

KeyError: 'counts'

neighbourhood_group의 값에 따른 neighbourhood컬럼 값의 갯수를 구하여라

In [40]:
df[['neighbourhood_group','neighbourhood']].groupby(['neighbourhood_group','neighbourhood'],as_index=False).size()

    neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]

neighbourhood_group의 값에 따른 neighbourhood컬럼 값 중 neighbourhood_group그룹의 최댓값들을 출력하라

In [49]:
ans = df[['neighbourhood_group','neighbourhood']].groupby(['neighbourhood_group','neighbourhood'],as_index=False).size()
ans.sort_values(['neighbourhood_group','size'],ascending=[True,False]).drop_duplicates('neighbourhood_group',keep='first')

    neighbourhood_group neighbourhood  size
18                Bronx   Kingsbridge    70
93             Brooklyn  Williamsburg  3920
105           Manhattan        Harlem  2658
128              Queens       Astoria   900
212       Staten Island    St. George    48

neighbourhood_group 값에 따른 price값의 평균, 분산, 최대, 최소 값을 구하여라

In [54]:
df[['neighbourhood_group','price']].groupby('neighbourhood_group').agg(['mean','var','max','min'])

                          price
                           mean           var    max min
neighbourhood_group
Bronx                 87.496792  11386.885081   2500   0
Brooklyn             124.383207  34921.719135  10000   0
Manhattan            196.875814  84904.159185  10000   0
Queens                99.517649  27923.130227  10000  10
Staten Island        114.812332  77073.088342   5000  13

neighbourhood_group 값에 따른 reviews_per_month 평균, 분산, 최대, 최소 값을 구하여라

In [56]:
df[['neighbourhood_group','reviews_per_month']].groupby('neighbourhood_group').agg(['mean','var','max','min'])

                    reviews_per_month
                                 mean       var    max   min
neighbourhood_group
Bronx                        1.837831  2.799878  10.34  0.02
Brooklyn                     1.283212  2.299040  14.00  0.01
Manhattan                    1.272131  2.651206  58.50  0.01
Queens                       1.941200  4.897848  20.94  0.01
Staten Island                1.872580  2.840895  10.12  0.02

neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 구하라

In [58]:
df[['neighbourhood_group','neighbourhood','price']].groupby(['neighbourhood','neighbourhood_group']).mean()

                                          price
neighbourhood   neighbourhood_group
Allerton        Bronx                 87.595238
Arden Heights   Staten Island         67.250000
Arrochar        Staten Island        115.000000
Arverne         Queens               171.779221
Astoria         Queens               117.187778
...                                         ...
Windsor Terrace Brooklyn             138.993631
Woodhaven       Queens                67.170455
Woodlawn        Bronx                 60.090909
Woodrow         Staten Island        700.000000
Woodside        Queens                85.097872

[221 rows x 1 columns]

neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하라

In [60]:
df[['neighbourhood_group','neighbourhood','price']].groupby(['neighbourhood','neighbourhood_group']).mean().unstack()

                         price
neighbourhood_group      Bronx    Brooklyn Manhattan      Queens Staten Island
neighbourhood
Allerton             87.595238         NaN       NaN         NaN           NaN
Arden Heights              NaN         NaN       NaN         NaN         67.25
Arrochar                   NaN         NaN       NaN         NaN        115.00
Arverne                    NaN         NaN       NaN  171.779221           NaN
Astoria                    NaN         NaN       NaN  117.187778           NaN
...                        ...         ...       ...         ...           ...
Windsor Terrace            NaN  138.993631       NaN         NaN           NaN
Woodhaven                  NaN         NaN       NaN   67.170455           NaN
Woodlawn             60.090909         NaN       NaN         NaN           NaN
Woodrow                    NaN         NaN       NaN         NaN        700.00
Woodside                   NaN         NaN       NaN   85.097872           NaN

[221 rows x 5 columns]

neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하고 nan 값은 -999값으로 채워라

In [66]:
ans=df.groupby(['neighbourhood','neighbourhood_group']).price.mean().unstack().fillna(-999)
ans

neighbourhood_group,Bronx,Brooklyn,Manhattan,Queens,Staten Island
neighbourhood,,,,,
Allerton,87.595238,-999.000000,-999.0,-999.000000,-999.00
Arden Heights,-999.000000,-999.000000,-999.0,-999.000000,67.25
Arrochar,-999.000000,-999.000000,-999.0,-999.000000,115.00
Arverne,-999.000000,-999.000000,-999.0,171.779221,-999.00
Astoria,-999.000000,-999.000000,-999.0,117.187778,-999.00
...,...,...,...,...,...
Windsor Terrace,-999.000000,138.993631,-999.0,-999.000000,-999.00
Woodhaven,-999.000000,-999.000000,-999.0,67.170455,-999.00
Woodlawn,60.090909,-999.000000,-999.0,-999.000000,-999.00
Woodrow,-999.000000,-999.000000,-999.0,-999.000000,700.00
Woodside,-999.000000,-999.000000,-999.0,85.097872,-999.00

데이터중 neighbourhood_group 값이 Queens값을 가지는 데이터들 중 neighbourhood 그룹별로 price값의 평균, 분산, 최대, 최소값을 구하라

In [71]:
df[df.neighbourhood_group=='Queens'].groupby('neighbourhood').price.agg(['mean','var','max','min'])

                           mean            var    max  min
neighbourhood
Arverne              171.779221   37383.411141   1500   35
Astoria              117.187778  122428.811196  10000   25
Bay Terrace          142.000000    6816.400000    258   32
Bayside              157.948718  166106.470985   2600   30
Bayswater             87.470588    2330.889706    230   45
Belle Harbor         171.500000    8226.571429    350   85
Bellerose             99.357143    3093.016484    240   42
Breezy Point         213.333333    1008.333333    250  195
Briarwood            105.875000   18503.165909   1000   30
Cambria Heights       81.730769    2960.604615    250   31
College Point         88.000000    6445.555556    400   44
Corona                59.171875    2430.557292    359   23
Ditmars Steinway      95.029126    4214.112785    600   22
Douglaston            82.750000    2347.071429    178   40
East Elmhurst         81.183784    4369.487779    700   16
Edgemere              94.727273    4219.418182    200   40
Elmhurst              80.459916    3896.563005    443   15
Far Rockaway         165.862069   52575.980296    900   35
Flushing              93.514085   12417.177448   1500   15
Forest Hills         121.625000   44533.368881   2350   16
Fresh Meadows         99.500000    6394.451613    375   39
Glendale              90.796296    3230.882250    299   25
Hollis                88.642857    1483.016484    175   50
Holliswood           135.750000    5091.583333    239   79
Howard Beach         115.400000    4241.936842    250   40
Jackson Heights       80.897849    2150.470590    260   23
Jamaica               95.770563    8067.047130   1000   10
Jamaica Estates      182.947368   29006.052632    750   35
Jamaica Hills        132.125000   11304.696429    325   50
Kew Gardens           88.375000    2632.306452    219   35
Kew Gardens Hills    112.307692    6230.621538    399   40
Laurelton             95.333333    4355.529412    254   34
Little Neck           75.200000    2368.700000    149   32
Long Island City     127.465549   15529.503009   2000   30
Maspeth               83.645455    2223.607089    245   11
Middle Village       109.580645    3537.118280    265   28
Neponsit             274.666667    5625.333333    350  200
Ozone Park            85.274194    1705.415389    200   25
Queens Village        83.933333    2386.470056    320   25
Rego Park             83.877358    3659.003863    300   21
Richmond Hill         87.117021    3474.147449    300   28
Ridgewood             77.184397    2629.311889    375   20
Rockaway Beach       132.178571    6254.622078    545   49
Rosedale              76.694915    2963.939801    350   22
South Ozone Park      82.400000    4619.989744    400   29
Springfield Gardens   94.235294    2490.848739    300   40
St. Albans           100.828947    9489.903684    600   25
Sunnyside             84.865014    2727.746922    600   12
Whitestone           107.545455   13632.072727    400   35
Woodhaven             67.170455    1642.464864    250   10
Woodside              85.097872    5001.900636    500   28

데이터중 neighbourhood_group 값에 따른 room_type 컬럼의 숫자를 구하고 neighbourhood_group 값을 기준으로 각 값의 비율을 구하여라

In [85]:
ww = df[['neighbourhood_group','room_type']].groupby(['neighbourhood_group','room_type'],as_index=False).size()
lst = []
for x in df.neighbourhood_group.value_counts()[ww.neighbourhood_group.unique()].values:
    for i in range(3):
      lst.append(x)

In [87]:
ww.loc[:,'ratio'] = ww['size'] / pd.Series(lst)
ww

   neighbourhood_group        room_type   size     ratio
0                Bronx  Entire home/apt    379  0.347388
1                Bronx     Private room    652  0.597617
2                Bronx      Shared room     60  0.054995
3             Brooklyn  Entire home/apt   9559  0.475478
4             Brooklyn     Private room  10132  0.503979
5             Brooklyn      Shared room    413  0.020543
6            Manhattan  Entire home/apt  13199  0.609344
7            Manhattan     Private room   7982  0.368496
8            Manhattan      Shared room    480  0.022160
9               Queens  Entire home/apt   2096  0.369926
10              Queens     Private room   3372  0.595129
11              Queens      Shared room    198  0.034945
12       Staten Island  Entire home/apt    176  0.471850
13       Staten Island     Private room    188  0.504021
14       Staten Island      Shared room      9  0.024129

In [141]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv')
df

,Unnamed: 0,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt
0,0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144
1,1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291
2,2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887
3,3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171
4,4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476
10123,10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764
10124,10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291
10125,10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395
10126,10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294

In [90]:
print("행:",df.shape[0])
print("열:",df.shape[1])

행: 10127
열: 19

Income_Category의 카테고리를 map 함수를 이용하여 다음과 같이 변경하여 newIncome 컬럼에 매핑하라 Unknown : N
Less than $40K : a
$40K - $60K : b
$60K - $80K : c
$80K - $120K : d
$120K +’ : e

In [100]:
dic = {
    'Unknown'        : 'N',
    'Less than $40K' : 'a',
    '$40K - $60K'    : 'b',
    '$60K - $80K'    : 'c',
    '$80K - $120K'   : 'd',
    '$120K +'        : 'e'
}
df['newIncome'] = df.Income_Category.map(lambda x:dic[x])
ans = df['newIncome']
ans

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

Income_Category의 카테고리를 apply 함수를 이용하여 다음과 같이 변경하여 newIncome 컬럼에 매핑하라 Unknown : N
Less than $40K : a
$40K - $60K : b
$60K - $80K : c
$80K - $120K : d
$120K +’ : e

In [116]:
def changeCategory(x):
    if x =='Unknown':
        return 'N'
    elif x =='Less than $40K':
        return 'a'
    elif x =='$40K - $60K':
        return 'b'
    elif x =='$60K - $80K':
        return 'c'
    elif x =='$80K - $120K':
        return 'd'
    elif x =='$120K +' :
        return 'e'

df['newIncome']  =df.Income_Category.apply(changeCategory)

Ans = df['newIncome']
Ans

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

Customer_Age의 값을 이용하여 나이 구간을 AgeState 컬럼으로 정의하라. (0~9 : 0 , 10~19 :10 , 20~29 :20 … 각 구간의 빈도수를 출력하라

In [122]:
df['AgeState'] = df['Customer_Age'].map(lambda x:x//10*10)
df['AgeState'].value_counts().sort_index()

AgeState
20     195
30    1841
40    4561
50    2998
60     530
70       2
Name: count, dtype: int64

Education_Level의 값중 Graduate단어가 포함되는 값은 1 그렇지 않은 경우에는 0으로 변경하여 newEduLevel 컬럼을 정의하고 빈도수를 출력하라

In [126]:
df['newEduLevel'] = df['Education_Level'].map(lambda x: 1 if 'Graduate' in x else 0)
df['newEduLevel']

0        0
1        1
2        1
3        0
4        0
        ..
10122    1
10123    0
10124    0
10125    1
10126    1
Name: newEduLevel, Length: 10127, dtype: int64

Credit_Limit 컬럼값이 4500 이상인 경우 1 그외의 경우에는 모두 0으로 하는 newLimit 정의하라. newLimit 각 값들의 빈도수를 출력하라

In [128]:
df['newLimit'] = df['Credit_Limit'].map(lambda x : 1 if x>=4500 else 0)
df.newLimit.value_counts()

newLimit
1    5096
0    5031
Name: count, dtype: int64

Marital_Status 컬럼값이 Married 이고 Card_Category 컬럼의 값이 Platinum인 경우 1 그외의 경우에는 모두 0으로 하는 newState컬럼을 정의하라. newState의 각 값들의 빈도수를 출력하라

In [139]:
def check(x):
  if x.Marital_Status == 'Married' and x.Card_Category =='Platinum':
    return 1
  else:
    return 0

df['newState'] = df.apply(check,axis=1)
ans = df['newState'].value_counts()
ans

newState
0    10120
1        7
Name: count, dtype: int64

Gender 컬럼값 M인 경우 male F인 경우 female로 값을 변경하여 Gender 컬럼에 새롭게 정의하라. 각 value의 빈도를 출력하라

In [142]:
df['Gender'] = df['Gender'].map(lambda x : 'male' if x=='M' else 'female')
df['Gender'].value_counts()

Gender
female    5358
male      4769
Name: count, dtype: int64

In [175]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   object
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: float64(12), object(1)
memory usage: 667.8+ KB

Yr_Mo_Dy을 판다스에서 인식할 수 있는 datetime64타입으로 변경하라

In [178]:
df['Yr_Mo_Dy'] = pd.to_datetime(df.Yr_Mo_Dy)
Ans = df['Yr_Mo_Dy']
Ans

0      2061-01-01
1      2061-01-02
2      2061-01-03
3      2061-01-04
4      2061-01-05
          ...
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   datetime64[ns]
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 667.8 KB

Yr_Mo_Dy에 존재하는 년도의 유일값을 모두 출력하라

In [155]:
ans = df['Yr_Mo_Dy'].dt.year.unique()
ans

array([2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978], dtype=int32)

weekday컬럼을 만들고 요일별로 매핑하라 ( 월요일: 0 ~ 일요일 :6)

In [157]:
dir(df.Yr_Mo_Dy.dt)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accessors',
 '_add_delegate_accessors',
 '_constructor',
 '_delegate_method',
 '_delegate_property_get',
 '_delegate_property_set',
 '_dir_additions',
 '_dir_deletions',
 '_freeze',
 '_get_values',
 '_hidden_attrs',
 '_parent',
 '_reset_cache',
 'as_unit',
 'ceil',
 'date',
 'day',
 'day_name',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'floor',
 'freq',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'isocalendar',
 'microsecond',
 'minute',
 'month',
 'month_name',
 'nanosecond',
 'normalize',
 'quarter',
 'round',
 'second',
 'strftime',
 'time',
 'timetz',
 'to_period',
 'to_pydatetime',
 'tz',
 'tz_convert',
 'tz_localize',
 'unit',
 'weekday',
 'year']

In [163]:
df['weekday']=df.Yr_Mo_Dy.dt.day_of_week
df['weekday']

0       5
1       6
2       0
3       1
4       2
       ..
6569    2
6570    3
6571    4
6572    5
6573    6
Name: weekday, Length: 6574, dtype: int32

weekday컬럼을 기준으로 주말이면 1 평일이면 0의 값을 가지는 WeekCheck 컬럼을 만들어라

In [165]:
df['WeekCheck'] = df['weekday'].map(lambda x : 1 if (x==5 or x==6) else 0 )
df['WeekCheck']

0       1
1       1
2       0
3       0
4       0
       ..
6569    0
6570    0
6571    0
6572    1
6573    1
Name: WeekCheck, Length: 6574, dtype: int64

년도, 일자 상관없이 모든 컬럼의 각 달의 평균을 구하여라

In [181]:
ans = df.groupby(df.Yr_Mo_Dy.dt.month,as_index=True).mean()
ans

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,,
1,2025-02-04 22:40:00.000000000,14.847325,12.914560,13.299624,7.199498,11.667734,8.054839,11.819355,9.512047,9.543208,10.053566,14.550520,18.028763
2,2025-02-20 00:22:40.629921280,13.710906,12.111122,12.879132,6.942411,11.551772,7.633858,11.206024,9.341437,9.313169,9.518051,13.728898,17.156142
3,2025-04-05 04:00:00.000000000,13.158687,11.505842,12.648118,7.265907,11.554516,7.959409,11.310179,9.635896,9.700324,10.096953,13.810609,16.909317
4,2025-05-05 16:00:00.000000000,12.555648,10.429759,12.204815,6.898037,10.677667,7.441389,10.221315,8.909056,8.930870,9.158019,12.664759,14.937611
5,2025-06-05 04:00:00.000000000,11.724032,10.145619,11.550394,6.307487,10.224301,6.942061,8.797738,8.452903,8.040806,8.524857,12.767258,13.736039
6,2025-07-05 16:00:00.000000000,10.451317,8.949704,10.361315,5.652278,9.529926,6.410093,8.009556,7.920796,7.639796,7.729185,12.246407,12.861818
7,2025-08-05 04:00:00.000000000,9.992007,8.357778,9.349642,5.416935,9.302634,5.972348,7.843501,7.262760,7.544480,7.321416,11.676505,12.800789
8,2025-09-05 04:00:00.000000000,10.213411,8.415143,9.993441,5.270681,8.901559,5.891057,7.772312,6.842025,7.240573,7.002783,11.110090,12.565943
9,2025-10-05 16:00:00.000000000,11.458519,9.981002,10.756883,5.615176,9.766315,6.566222,8.609722,7.745677,7.610556,7.689278,12.686389,14.761963
10,2025-11-05 04:00:00.000000000,12.660610,11.010681,11.453943,6.065215,10.550251,7.159910,9.387778,8.726308,8.347181,8.850376,14.155323,16.697151
11,2025-12-05 16:00:00.000000000,13.200722,11.639500,12.293407,6.247611,10.501130,7.134333,10.814861,8.427167,8.604000,8.943167,13.815741,18.114185
12,2026-01-05 04:00:00.000000000,14.446398,12.353602,13.212276,6.829910,11.301254,7.963710,11.849050,9.209355,9.447258,9.627670,14.259516,18.697599

모든 결측치는 컬럼기준 직전의 값으로 대체하고 첫번째 행에 결측치가 있을경우 뒤에있는 값으로 대채하라

In [185]:
df=df.fillna(method='ffill').fillna(method='bfill')

<ipython-input-185-20ca92daeacb>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='ffill').fillna(method='bfill')

In [186]:
df.isnull().sum()

Yr_Mo_Dy    0
RPT         0
VAL         0
ROS         0
KIL         0
SHA         0
BIR         0
DUB         0
CLA         0
MUL         0
CLO         0
BEL         0
MAL         0
dtype: int64

일자별 영어요일 이름을 dayName 컬럼에 저장하라

In [196]:
df['dayName']=df.Yr_Mo_Dy.dt.day_name()
df['dayName']

0        Saturday
1          Sunday
2          Monday
3         Tuesday
4       Wednesday
          ...
6569    Wednesday
6570     Thursday
6571       Friday
6572     Saturday
6573       Sunday
Name: dayName, Length: 6574, dtype: object

일자별 각 PM10등급의 빈도수를 파악하라

In [259]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/seoul_pm.csv')
df

,(년-월-일:시),PM10등급,PM10,PM2.5등급,PM2.5,오존등급,오존,이산화질소등급,이산화질소,일산화탄소등급,일산화탄소,아황산가스등급,아황산가스
0,2021-05-15:15,보통,47.0,보통,19.0,좋음,0.017,좋음,0.023,좋음,0.4,좋음,0.003
1,2021-05-15:14,보통,43.0,보통,20.0,좋음,0.024,좋음,0.019,좋음,0.3,좋음,0.003
2,2021-05-15:13,보통,34.0,보통,24.0,보통,0.035,좋음,0.017,좋음,0.4,좋음,0.004
3,2021-05-15:12,보통,41.0,보통,27.0,보통,0.037,좋음,0.020,좋음,0.4,좋음,0.004
4,2021-05-15:11,보통,51.0,보통,34.0,보통,0.033,좋음,0.023,좋음,0.4,좋음,0.005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234,2021-03-25:05,보통,39.0,보통,18.0,좋음,0.026,좋음,0.025,좋음,0.4,좋음,0.003
1235,2021-03-25:04,보통,34.0,좋음,15.0,좋음,0.017,보통,0.033,좋음,0.4,좋음,0.002
1236,2021-03-25:03,보통,35.0,좋음,13.0,좋음,0.029,좋음,0.025,좋음,0.4,좋음,0.003
1237,2021-03-25:02,보통,35.0,좋음,13.0,보통,0.031,좋음,0.025,좋음,0.3,좋음,0.003
1238,2021-03-25:01,보통,42.0,좋음,13.0,좋음,0.022,보통,0.037,좋음,0.4,좋음,0.003

In [260]:
df = df.rename(columns={'(년-월-일:시)':'date'})
# df[df.date.str[-2:]=='24']

In [261]:
import datetime
# 시각이 24라면 적절한
def date_ft(x):
  if x[-2:] != '24':
    x = x.replace(':',' ')
    return pd.to_datetime(x)

  else:
    date = pd.to_datetime(x.split(':')[0]) + datetime.timedelta(days=1)
    return date

In [262]:
df.loc[:,'date'] = df['date'].apply(date_ft)

In [270]:
df['date'] = pd.to_datetime(df.date)

In [271]:
df['dayName'] = df['date'].dt.day_name()

In [282]:
ans = df.groupby(['dayName','PM10등급'],as_index=False).size()

In [283]:
ans.pivot(index='dayName',columns='PM10등급',values='size').fillna(0)

PM10등급       나쁨  매우나쁨     보통    좋음
dayName
Friday     31.0  17.0  120.0  21.0
Monday      1.0  21.0   83.0  63.0
Saturday   31.0  27.0   71.0  54.0
Sunday      2.0   1.0   67.0  98.0
Thursday   41.0   0.0  144.0   5.0
Tuesday    13.0  10.0   71.0  74.0
Wednesday  26.0   0.0   95.0  46.0

시간이 연속적으로 존재하며 결측치가 없는지 확인하라

In [292]:
df.date.diff().dropna().unique()

<TimedeltaArray>
['-1 days +23:00:00']
Length: 1, dtype: timedelta64[ns]

오전 10시와 오후 10시(22시)의 PM10의 평균값을 각각 구하여라

In [302]:
df.groupby(df['date'].dt.hour)['PM10'].mean()[10]
df.groupby(df['date'].dt.hour)['PM10'].mean()[22]

69.94117647058823

In [305]:
df[df['date'].dt.hour==10]['PM10'].mean()

70.38461538461539

날짜 컬럼을 index로 만들어라

In [308]:
df.set_index('date',inplace=True,drop=True)

KeyError: "None of ['date'] are in the columns"

In [309]:
df

,PM10등급,PM10,PM2.5등급,PM2.5,오존등급,오존,이산화질소등급,이산화질소,일산화탄소등급,일산화탄소,아황산가스등급,아황산가스,dayName
date,,,,,,,,,,,,,
2021-05-15 15:00:00,보통,47.0,보통,19.0,좋음,0.017,좋음,0.023,좋음,0.4,좋음,0.003,Saturday
2021-05-15 14:00:00,보통,43.0,보통,20.0,좋음,0.024,좋음,0.019,좋음,0.3,좋음,0.003,Saturday
2021-05-15 13:00:00,보통,34.0,보통,24.0,보통,0.035,좋음,0.017,좋음,0.4,좋음,0.004,Saturday
2021-05-15 12:00:00,보통,41.0,보통,27.0,보통,0.037,좋음,0.020,좋음,0.4,좋음,0.004,Saturday
2021-05-15 11:00:00,보통,51.0,보통,34.0,보통,0.033,좋음,0.023,좋음,0.4,좋음,0.005,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-25 05:00:00,보통,39.0,보통,18.0,좋음,0.026,좋음,0.025,좋음,0.4,좋음,0.003,Thursday
2021-03-25 04:00:00,보통,34.0,좋음,15.0,좋음,0.017,보통,0.033,좋음,0.4,좋음,0.002,Thursday
2021-03-25 03:00:00,보통,35.0,좋음,13.0,좋음,0.029,좋음,0.025,좋음,0.4,좋음,0.003,Thursday
2021-03-25 02:00:00,보통,35.0,좋음,13.0,보통,0.031,좋음,0.025,좋음,0.3,좋음,0.003,Thursday
2021-03-25 01:00:00,보통,42.0,좋음,13.0,좋음,0.022,보통,0.037,좋음,0.4,좋음,0.003,Thursday

In [312]:
df['date']

KeyError: 'date'

In [314]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/under5MortalityRate.csv')
df

,Location,Period,Indicator,Dim1,First Tooltip
0,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Both sexes,60.27 [47.44-74.62]
1,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Male,63.83 [50.04-79.16]
2,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Female,56.57 [44.54-70.18]
3,Afghanistan,2018,Under-five mortality rate (probability of dyin...,Both sexes,62.54 [50.64-75.41]
4,Afghanistan,2018,Under-five mortality rate (probability of dyin...,Male,66.08 [53.41-79.76]
...,...,...,...,...,...
29994,Timor-Leste,2002,Under-five mortality rate (probability of dyin...,Both sexes,96.97 [87.36-107.7]
29995,Timor-Leste,2002,Under-five mortality rate (probability of dyin...,Male,102.6 [92.14-114]
29996,Timor-Leste,2002,Under-five mortality rate (probability of dyin...,Female,91.04 [81.92-101.5]
29997,Timor-Leste,2001,Under-five mortality rate (probability of dyin...,Both sexes,102.5 [92.72-113.3]
29998,Timor-Leste,2001,Under-five mortality rate (probability of dyin...,Male,108.2 [97.57-120]

Indicator을 삭제하고 First Tooltip 컬럼에서 신뢰구간에 해당하는 표현을 지워라

In [316]:
df.drop('Indicator',axis=1,inplace=True)
df['First Tooltip'] =df['First Tooltip'].map(lambda x :float(x.split("[")[0]))
ans = df

KeyError: "['Indicator'] not found in axis"

In [317]:
ans = df
ans

          Location  Period        Dim1  First Tooltip
0      Afghanistan    2019  Both sexes          60.27
1      Afghanistan    2019        Male          63.83
2      Afghanistan    2019      Female          56.57
3      Afghanistan    2018  Both sexes          62.54
4      Afghanistan    2018        Male          66.08
...            ...     ...         ...            ...
29994  Timor-Leste    2002  Both sexes          96.97
29995  Timor-Leste    2002        Male         102.60
29996  Timor-Leste    2002      Female          91.04
29997  Timor-Leste    2001  Both sexes         102.50
29998  Timor-Leste    2001        Male         108.20

[29999 rows x 4 columns]

년도가 2015년 이상, Dim1이 Both sexes인 케이스만 추출하라

In [325]:
df = df[(df.Period >= 2015) & (df['Dim1']=='Both sexes')]
df

          Location  Period        Dim1  First Tooltip
0      Afghanistan    2019  Both sexes          60.27
3      Afghanistan    2018  Both sexes          62.54
6      Afghanistan    2017  Both sexes          64.94
9      Afghanistan    2016  Both sexes          67.57
12     Afghanistan    2015  Both sexes          70.44
...            ...     ...         ...            ...
29943  Timor-Leste    2019  Both sexes          44.22
29946  Timor-Leste    2018  Both sexes          45.62
29949  Timor-Leste    2017  Both sexes          47.27
29952  Timor-Leste    2016  Both sexes          49.01
29955  Timor-Leste    2015  Both sexes          50.76

[860 rows x 4 columns]

84번 문제에서 추출한 데이터로 아래와 같이 나라에 따른 년도별 사망률을 데이터 프레임화 하라

In [331]:
df.pivot(index='Location',columns='Period',values='First Tooltip')

Period                                      2015   2016   2017   2018   2019
Location
Afghanistan                                70.44  67.57  64.94  62.54  60.27
Albania                                     9.57   9.42   9.42   9.53   9.68
Algeria                                    25.18  24.79  24.32  23.81  23.26
Andorra                                     3.53   3.37   3.22   3.09   2.97
Angola                                     88.20  84.21  80.62  77.67  74.69
...                                          ...    ...    ...    ...    ...
Syrian Arab Republic                       23.18  23.27  22.97  22.11  21.53
Tajikistan                                 37.75  36.82  35.81  34.80  33.78
Thailand                                   10.80  10.32   9.86   9.42   9.01
The former Yugoslav Republic of Macedonia  12.97  11.97   9.94   7.83   6.12
Timor-Leste                                50.76  49.01  47.27  45.62  44.22

[172 rows x 5 columns]

Dim1에 따른 년도별 사망비율의 평균을 구하라