<a href="https://colab.research.google.com/github/mini1115/TIL/blob/master/%EB%B9%85%EB%B6%84%EA%B8%B0_%EC%8B%A4%EA%B8%B0/part1/Data_Manim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv',sep='\t')
df.head(5)

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18

In [62]:
# 데이터 행과 열의 갯수
df.shape
print("행:",df.shape[0])
print("열: ",df.shape[1])

행: 51490
열:  61

In [63]:
# 전체 컬럼을 출력하라
ans = df.columns
ans

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHeraldKills', 't2_ban1', 't2_ban2', 't2_ban3', 't2_ban4',
       't2_ban5'],
      dtype='object')

In [64]:
#6번째 컬럼값을 출력하라
ans = df.iloc[:,5].dtype
ans

dtype('int64')

In [65]:
# 데이터셋의 인덱스 구성
df.index

RangeIndex(start=0, stop=51490, step=1)

In [66]:
# 6번째 컬럼의 3번째 값은 무엇인가?
df.iloc[2,5]

2

In [67]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv',encoding='EUC-KR')
df

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
0,22448,2018-01-01,제주시,도두동,32249.987,3418.266,102709.092,138377.345,39.556,29.167,5.0,0.0,2.50
1,22449,2018-01-01,제주시,외도동,213500.997,10341.172,112692.789,336534.958,32.900,30.900,5.0,0.0,2.50
2,22450,2018-01-01,제주시,이도2동,1212382.218,96920.834,541194.481,1850497.533,29.538,35.692,2.9,0.0,2.40
3,22451,2018-01-01,제주시,일도1동,33991.653,6034.253,72155.919,112181.825,30.000,23.500,2.9,0.0,2.40
4,22452,2018-01-01,서귀포시,대천동,155036.925,9403.969,150882.409,315323.303,41.583,14.375,5.1,0.0,2.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9616,32064,2020-04-30,서귀포시,표선면,228260.005,16891.732,152832.449,397984.186,44.514,34.054,18.1,0.0,4.70
9617,32065,2020-04-30,제주시,한림읍,459959.064,26007.122,249700.419,735666.605,48.609,61.377,18.0,0.0,4.35
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.00
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.50
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.80

In [68]:
# 데이터 마지막 3개행을 출력하라
df.tail(3)

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.0
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.5
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.8

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB

In [70]:
# 수치형 변수를 가진 컬럼을 출력하라
ans = df.select_dtypes(include='float64' or 'int64').columns
ans

Index(['거주인구', '근무인구', '방문인구', '총 유동인구', '평균 속도', '평균 소요 시간', '평균 기온', '일강수량',
       '평균 풍속'],
      dtype='object')

In [71]:
# 범주형 변수를 가진 컬럼을 출력하라
ans = df.select_dtypes(include='O').columns
ans

Index(['일자', '시도명', '읍면동명'], dtype='object')

In [72]:
# 각 컬럼의 결측치 숫자를 파악하라
ans = df.isnull().sum()
ans

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

In [73]:
# 각 컬럼의 데이터수, 데이터타입을 한번에 확인하라
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB

In [74]:
# 각 수치형 변수의 분포(사분위, 평균, 표준편차, 최대 , 최소)를 확인하라
df.describe()

,id,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
count,9621.000000,9.621000e+03,9621.000000,9621.000000,9.621000e+03,9621.000000,9621.000000,9621.000000,9621.000000,9621.000000
mean,27258.000000,3.174315e+05,35471.201510,195889.561802,5.487922e+05,41.109084,37.215873,13.550828,6.972426,2.753171
std,2777.487804,2.982079e+05,40381.214775,140706.090325,4.608802e+05,8.758631,12.993786,7.745515,27.617260,1.498538
min,22448.000000,9.305552e+03,1407.936000,11538.322000,2.225181e+04,24.333000,12.667000,-9.600000,0.000000,0.000000
25%,24853.000000,9.539939e+04,12074.498000,99632.153000,2.216910e+05,34.250000,27.889000,7.600000,0.000000,1.700000
50%,27258.000000,2.221105e+05,21960.928000,152805.335000,3.866935e+05,39.640000,34.500000,13.400000,0.000000,2.400000
75%,29663.000000,4.106671e+05,40192.032000,236325.109000,6.406918e+05,49.105000,46.176000,19.700000,1.500000,3.400000
max,32068.000000,1.364504e+06,263476.965000,723459.209000,2.066484e+06,103.000000,172.200000,30.400000,587.500000,13.333000

In [75]:
# 거주인구 컬럼의 값들을 출력하라
ans = df['거주인구']
ans

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: 거주인구, Length: 9621, dtype: float64

In [76]:
# 평균 속도 컬럼의 4분위 범위(IQR) 값을 구하여라
ans = df['평균 속도'].quantile(0.75)-df['평균 속도'].quantile(0.25)
ans

14.854999999999997

In [77]:
# 읍면동명 컬럼의 유일값 갯수를 출력하라

df['읍면동명'].nunique()

41

In [78]:
# 읍면동명 컬럼의 유일값을 모두 출력하라
df['읍면동명'].unique()

array(['도두동', '외도동', '이도2동', '일도1동', '대천동', '서홍동', '한경면', '송산동', '조천읍',
       '일도2동', '영천동', '예래동', '대륜동', '삼도1동', '이호동', '건입동', '중앙동', '삼양동',
       '삼도2동', '이도1동', '남원읍', '대정읍', '정방동', '효돈동', '아라동', '한림읍', '구좌읍',
       '용담1동', '오라동', '화북동', '연동', '표선면', '중문동', '성산읍', '안덕면', '천지동',
       '노형동', '동홍동', '용담2동', '봉개동', '애월읍'], dtype=object)

In [79]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [80]:
# quantity컬럼 값이 3인 데이터를 추출하여 첫 5행을 출력하라
df.iloc[(df['quantity']==3).values].head(5)
df.loc[df['quantity']==3].head(5)

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75

In [81]:
# quantity컬럼 값이 3인 데이터를 추출하여 index를 0부터 정렬하고 첫 5행을 출력하라
df.loc[df['quantity']==3].head().reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price
0,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
1,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
2,284,3,Canned Soft Drink,[Diet Coke],$3.75
3,338,3,Bottled Water,NaN,$3.27
4,350,3,Canned Soft Drink,[Sprite],$3.75

In [82]:
# quantity , item_price 두개의 컬럼으로 구성된 새로운 데이터 프레임을 정의하라
new_data = df[['quantity','item_price']]
new_data

      quantity item_price
0            1     $2.39
1            1     $3.39
2            1     $3.39
3            1     $2.39
4            2    $16.98
...        ...        ...
4617         1    $11.75
4618         1    $11.75
4619         1    $11.25
4620         1     $8.75
4621         1     $8.75

[4622 rows x 2 columns]

In [83]:
# item_price 컬럼의 달러표시 문자를 제거하고 float 타입으로 저장하여 new_price 컬럼에 저장하라
df['new_price'] = df['item_price'].str.replace('$','').astype(float)
df['new_price']

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: new_price, Length: 4622, dtype: float64

In [84]:
# new_price 컬럼이 5이하의 값을 가지는 데이터프레임을 추출하고, 전체 갯수를 구하여라
ans = len(df.loc[df['new_price']<=5])
ans

1652

In [85]:
# item_name명이 Chicken Salad Bowl 인 데이터 프레임을 추출하라고 index 값을 초기화 하여라
df.loc[df['item_name']== 'Chicken Salad Bowl'].reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
1,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50,22.50
2,94,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$22.50,22.50
3,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
4,137,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$17.50,17.50
...,...,...,...,...,...,...
105,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$17.50,17.50
106,1822,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",$11.25,11.25
107,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
108,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
109,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [86]:
# new_price값이 9 이하이고 item_name 값이 Chicken Salad Bowl 인 데이터 프레임을 추출하라
df.loc[(df['new_price']<=9) & (df.item_name=='Chicken Salad Bowl')]

,order_id,quantity,item_name,choice_description,item_price,new_price
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
256,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
526,220,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Sour ...",$8.75,8.75
528,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
529,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
568,234,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$8.75,8.75
585,240,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$8.75,8.75
693,286,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Sour Cream, Cheese, Lett...",$8.75,8.75
702,289,1,Chicken Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$8.75,8.75
762,314,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
1109,458,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
1460,592,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$8.75,8.75
1471,598,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
1483,602,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
1547,628,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
1601,649,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
1621,654,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
1756,709,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",$8.75,8.75
1977,798,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",$8.75,8.75
2031,818,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
2113,850,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",$8.75,8.75
2224,896,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Sour Cream,...",$8.75,8.75
2314,926,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream]]",$8.75,8.75
2728,1083,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75,8.75
2858,1136,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
2883,1145,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Sour ...",$8.75,8.75
2897,1152,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, Cheese]",$8.75,8.75
2989,1189,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
3033,1206,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",$8.75,8.75
3069,1222,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$8.75,8.75
3117,1243,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",$8.75,8.75
3259,1305,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
3261,1305,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
3310,1327,1,Chicken Salad Bowl,[Fresh Tomato Salsa],$8.75,8.75
3315,1329,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce]]",$8.75,8.75
3381,1357,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",$8.75,8.75
3411,1368,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Lettuce]]",$8.75,8.75
3623,1450,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",$8.75,8.75
3656,1461,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
3706,1483,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Chees...",$8.75,8.75
3712,1483,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Chees...",$8.75,8.75
3790,1517,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
3798,1521,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
3974,1592,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Lettu...",$8.75,8.75
3997,1601,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
4012,1606,1,Chicken Salad Bowl,[Fresh Tomato Salsa],$8.75,8.75
4035,1615,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
4064,1627,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4205,1679,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Chees...",$8.75,8.75
4207,1679,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75,8.75
4333,1730,1,Chicken Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Cheese]]",$8.75,8.75
4352,1738,1,Chicken Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$8.75,8.75
4439,1769,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4520,1797,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$8.75,8.75
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [87]:
# df의 new_price 컬럼 값에 따라 오름차순으로 정리하고 index를 초기화 하여라
df.sort_values('new_price').reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,471,1,Bottled Water,NaN,$1.09,1.09
1,338,1,Canned Soda,[Coca Cola],$1.09,1.09
2,1575,1,Canned Soda,[Dr. Pepper],$1.09,1.09
3,47,1,Canned Soda,[Dr. Pepper],$1.09,1.09
4,1014,1,Canned Soda,[Coca Cola],$1.09,1.09
...,...,...,...,...,...,...
4617,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
4618,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
4619,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
4620,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
4621,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25

In [88]:
# df의 item_name 컬럼 값중 Chips 포함하는 경우의 데이터를 출력하라
df.loc[df['item_name'].str.contains('Chips')]

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
6,3,1,Side of Chips,NaN,$1.69,1.69
10,5,1,Chips and Guacamole,NaN,$4.45,4.45
14,7,1,Chips and Guacamole,NaN,$4.45,4.45
...,...,...,...,...,...,...
4596,1826,1,Chips and Guacamole,NaN,$4.45,4.45
4600,1827,1,Chips and Guacamole,NaN,$4.45,4.45
4605,1828,1,Chips and Guacamole,NaN,$4.45,4.45
4613,1831,1,Chips,NaN,$2.15,2.15
4616,1832,1,Chips and Guacamole,NaN,$4.45,4.45

In [89]:
# df의 짝수번째 컬럼만을 포함하는 데이터프레임을 출력하라
df.iloc[:,::2]

      order_id                              item_name item_price
0            1           Chips and Fresh Tomato Salsa     $2.39
1            1                                   Izze     $3.39
2            1                       Nantucket Nectar     $3.39
3            1  Chips and Tomatillo-Green Chili Salsa     $2.39
4            2                           Chicken Bowl    $16.98
...        ...                                    ...        ...
4617      1833                          Steak Burrito    $11.75
4618      1833                          Steak Burrito    $11.75
4619      1834                     Chicken Salad Bowl    $11.25
4620      1834                     Chicken Salad Bowl     $8.75
4621      1834                     Chicken Salad Bowl     $8.75

[4622 rows x 3 columns]

In [90]:
df.loc[:,::2]

      order_id                              item_name item_price
0            1           Chips and Fresh Tomato Salsa     $2.39
1            1                                   Izze     $3.39
2            1                       Nantucket Nectar     $3.39
3            1  Chips and Tomatillo-Green Chili Salsa     $2.39
4            2                           Chicken Bowl    $16.98
...        ...                                    ...        ...
4617      1833                          Steak Burrito    $11.75
4618      1833                          Steak Burrito    $11.75
4619      1834                     Chicken Salad Bowl    $11.25
4620      1834                     Chicken Salad Bowl     $8.75
4621      1834                     Chicken Salad Bowl     $8.75

[4622 rows x 3 columns]

In [91]:
df.loc[(df['item_name']=='Steak Salad') | (df['item_name']=='Bowl')]

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
752,311,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
893,369,1,Steak Salad,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$8.99,8.99
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후, item_name를 기준으로 중복행이 있으면 제거하되 첫번째 케이스만 남겨라

In [92]:
new_column = df.loc[(df['item_name']=='Steak Salad') | (df['item_name']=='Bowl')]
new_column.drop_duplicates('item_name',keep='first')

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99

df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후, item_name를 기준으로 중복행이 있으면 제거하되 마지막 케이스만 남겨라

In [93]:
new_column = df.loc[(df['item_name']=='Steak Salad') | (df['item_name']=='Bowl')]
new_column.drop_duplicates('item_name',keep='last')

,order_id,quantity,item_name,choice_description,item_price,new_price
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

df의 데이터 중 new_price값이 new_price값의 평균값 이상을 가지는 데이터들을 인덱싱하라

In [94]:
data = df['new_price'].mean()
df.loc[df['new_price']>=data]

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

df의 데이터 중 item_name의 값이 Izze 데이터를 Fizzy Lizzy로 수정하라

In [95]:
df.loc[df['item_name']=='Izze','item_name']='Fizzy Lizzy'
df.loc[df['item_name']=='Fizzy Lizzy']

      order_id  quantity    item_name choice_description item_price  new_price
1            1         1  Fizzy Lizzy       [Clementine]     $3.39        3.39
24          12         1  Fizzy Lizzy       [Grapefruit]     $3.39        3.39
47          21         1  Fizzy Lizzy       [Blackberry]     $3.39        3.39
66          30         1  Fizzy Lizzy       [Blackberry]     $3.39        3.39
359        155         1  Fizzy Lizzy       [Blackberry]     $3.39        3.39
360        155         1  Fizzy Lizzy       [Grapefruit]     $3.39        3.39
430        186         1  Fizzy Lizzy       [Grapefruit]     $3.39        3.39
579        237         1  Fizzy Lizzy       [Clementine]     $3.39        3.39
580        237         1  Fizzy Lizzy       [Grapefruit]     $3.39        3.39
1059       436         1  Fizzy Lizzy       [Clementine]     $3.39        3.39
1213       495         1  Fizzy Lizzy       [Clementine]     $3.39        3.39
1611       651         1  Fizzy Lizzy       [Blackberry]     $3.39        3.39
1612       651         1  Fizzy Lizzy       [Blackberry]     $3.39        3.39
1680       680         1  Fizzy Lizzy       [Clementine]     $3.39        3.39
2088       842         1  Fizzy Lizzy       [Clementine]     $3.39        3.39
2619      1040         1  Fizzy Lizzy       [Clementine]     $3.39        3.39
2634      1046         1  Fizzy Lizzy       [Clementine]     $3.39        3.39
2758      1095         1  Fizzy Lizzy       [Blackberry]     $3.39        3.39
2891      1149         1  Fizzy Lizzy       [Blackberry]     $3.39        3.39
3669      1468         1  Fizzy Lizzy       [Blackberry]     $3.39        3.39

df의 데이터 중 choice_description 값이 NaN 인 데이터의 갯수를 구하여라

In [103]:
ans = df.loc[df['choice_description'].isna()]
len(ans)

1246

df의 데이터 중 choice_description 값이 NaN 인 데이터를 NoData 값으로 대체하라(loc 이용)

In [105]:
df.loc[df['choice_description'].isna(),'choice_description']='NoData'
df.loc[df['choice_description']=='NoData']

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
6,3,1,Side of Chips,NoData,$1.69,1.69
10,5,1,Chips and Guacamole,NoData,$4.45,4.45
14,7,1,Chips and Guacamole,NoData,$4.45,4.45
...,...,...,...,...,...,...
4600,1827,1,Chips and Guacamole,NoData,$4.45,4.45
4605,1828,1,Chips and Guacamole,NoData,$4.45,4.45
4613,1831,1,Chips,NoData,$2.15,2.15
4614,1831,1,Bottled Water,NoData,$1.50,1.50
4616,1832,1,Chips and Guacamole,NoData,$4.45,4.45

df의 데이터 중 choice_description 값에 Black이 들어가는 경우를 인덱싱하라

In [106]:
ans = df.loc[df['choice_description'].str.contains('Black')]
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
...,...,...,...,...,...,...
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25,11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25,9.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75

df의 데이터 중 choice_description 값에 Vegetables 들어가지 않는 경우의 갯수를 출력하라

In [108]:
ans = df.loc[~df['choice_description'].str.contains('Vegetables')]
len(ans)

3900

df의 데이터 중 item_name 값이 N으로 시작하는 데이터를 모두 추출하라

In [109]:
ans = df.loc[df['item_name'].str[0]=='N']
ans
#결측값 nan 시 오류 발생

,order_id,quantity,item_name,choice_description,item_price,new_price
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
173,77,1,Nantucket Nectar,[Apple],$3.39,3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78,6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39,3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78,6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39,3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39,3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39,3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39,3.39

In [111]:
ans2 = df.loc[df['item_name'].str.startswith('N')]
ans2

,order_id,quantity,item_name,choice_description,item_price,new_price
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
173,77,1,Nantucket Nectar,[Apple],$3.39,3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78,6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39,3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78,6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39,3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39,3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39,3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39,3.39

df의 데이터 중 item_name 값의 단어갯수가 15개 이상인 데이터를 인덱싱하라

In [113]:
ans = df.loc[df['item_name'].str.len()>=15]
ans

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
10,5,1,Chips and Guacamole,NoData,$4.45,4.45
...,...,...,...,...,...,...
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75,8.75
4616,1832,1,Chips and Guacamole,NoData,$4.45,4.45
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

df의 데이터 중 new_price값이 lst에 해당하는 경우의 데이터 프레임을 구하고 그 갯수를 출력하라 lst =[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]

In [117]:
lst =[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]
ans = df.loc[df['new_price'].isin(lst)]
len(ans)

1393

데이터를 로드하고 상위 5개 컬럼을 출력하라

In [177]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

데이터의 각 host_name의 빈도수를 구하고 host_name으로 정렬하여 상위 5개를 출력하라

In [127]:
df['host_name'].value_counts().sort_index().head()

host_name
'Cil                        1
(Ari) HENRY LEE             1
(Email hidden by Airbnb)    6
(Mary) Haiy                 1
-TheQueensCornerLot         1
Name: count, dtype: int64

데이터의 각 host_name의 빈도수를 구하고 <br/>빈도수 기준 내림차순 정렬한 데이터 프레임을 만들어라. 빈도수 컬럼은 counts로 명명하라

In [143]:
df['host_name'].value_counts().to_frame().rename(columns={'host_name':'counts'})

                   count
host_name
Michael              417
David                403
Sonder (NYC)         327
John                 294
Alex                 279
...                  ...
Rhonycs                1
Brandy-Courtney        1
Shanthony              1
Aurore And Jamila      1
Ilgar & Aysel          1

[11452 rows x 1 columns]

neighbourhood_group의 값에 따른 neighbourhood컬럼 값의 갯수를 구하여라

In [154]:
df[['neighbourhood_group','neighbourhood']].groupby(['neighbourhood_group','neighbourhood'],as_index=False).size()

    neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]

In [150]:
df['neighbourhood_group'].value_counts()

neighbourhood_group
Manhattan        21661
Brooklyn         20104
Queens            5666
Bronx             1091
Staten Island      373
Name: count, dtype: int64

neighbourhood_group의 값에 따른 neighbourhood컬럼 값 중 neighbourhood_group그룹의 최댓값들을 출력하라

In [159]:
df.groupby(['neighbourhood_group','neighbourhood'],as_index=False).size().groupby(['neighbourhood_group'],as_index=False).max()

  neighbourhood_group    neighbourhood  size
0               Bronx         Woodlawn    70
1            Brooklyn  Windsor Terrace  3920
2           Manhattan     West Village  2658
3              Queens         Woodside   900
4       Staten Island          Woodrow    48

neighbourhood_group 값에 따른 price값의 평균, 분산, 최대, 최소 값을 구하여라

In [161]:
df.groupby('neighbourhood_group')['price'].agg(['mean','var','max','min'])

                           mean           var    max  min
neighbourhood_group
Bronx                 87.496792  11386.885081   2500    0
Brooklyn             124.383207  34921.719135  10000    0
Manhattan            196.875814  84904.159185  10000    0
Queens                99.517649  27923.130227  10000   10
Staten Island        114.812332  77073.088342   5000   13

neighbourhood_group 값에 따른 reviews_per_month 평균, 분산, 최대, 최소 값을 구하여라

In [162]:
df.groupby('neighbourhood_group')['reviews_per_month'].agg(['mean','var','max','min'])

                         mean       var    max   min
neighbourhood_group
Bronx                1.837831  2.799878  10.34  0.02
Brooklyn             1.283212  2.299040  14.00  0.01
Manhattan            1.272131  2.651206  58.50  0.01
Queens               1.941200  4.897848  20.94  0.01
Staten Island        1.872580  2.840895  10.12  0.02

In [163]:
df[['neighbourhood_group','reviews_per_month']].groupby('neighbourhood_group').agg(['mean','var','max','min'])

                    reviews_per_month
                                 mean       var    max   min
neighbourhood_group
Bronx                        1.837831  2.799878  10.34  0.02
Brooklyn                     1.283212  2.299040  14.00  0.01
Manhattan                    1.272131  2.651206  58.50  0.01
Queens                       1.941200  4.897848  20.94  0.01
Staten Island                1.872580  2.840895  10.12  0.02

neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 구하라

In [166]:
df[['neighbourhood','neighbourhood_group','price']].groupby(['neighbourhood','neighbourhood_group']).agg(['mean'])

                                          price
                                           mean
neighbourhood   neighbourhood_group
Allerton        Bronx                 87.595238
Arden Heights   Staten Island         67.250000
Arrochar        Staten Island        115.000000
Arverne         Queens               171.779221
Astoria         Queens               117.187778
...                                         ...
Windsor Terrace Brooklyn             138.993631
Woodhaven       Queens                67.170455
Woodlawn        Bronx                 60.090909
Woodrow         Staten Island        700.000000
Woodside        Queens                85.097872

[221 rows x 1 columns]

neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하라

In [182]:
df[['neighbourhood','neighbourhood_group','price']].groupby(['neighbourhood','neighbourhood_group'],as_index=False).mean()

       neighbourhood neighbourhood_group       price
0           Allerton               Bronx   87.595238
1      Arden Heights       Staten Island   67.250000
2           Arrochar       Staten Island  115.000000
3            Arverne              Queens  171.779221
4            Astoria              Queens  117.187778
..               ...                 ...         ...
216  Windsor Terrace            Brooklyn  138.993631
217        Woodhaven              Queens   67.170455
218         Woodlawn               Bronx   60.090909
219          Woodrow       Staten Island  700.000000
220         Woodside              Queens   85.097872

[221 rows x 3 columns]

neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하고 nan 값은 -999값으로 채워라

In [195]:
ans = df.groupby(['neighbourhood','neighbourhood_group'])['price'].mean()
ans.unstack().fillna(-999)

neighbourhood_group,Bronx,Brooklyn,Manhattan,Queens,Staten Island
neighbourhood,,,,,
Allerton,87.595238,-999.000000,-999.0,-999.000000,-999.00
Arden Heights,-999.000000,-999.000000,-999.0,-999.000000,67.25
Arrochar,-999.000000,-999.000000,-999.0,-999.000000,115.00
Arverne,-999.000000,-999.000000,-999.0,171.779221,-999.00
Astoria,-999.000000,-999.000000,-999.0,117.187778,-999.00
...,...,...,...,...,...
Windsor Terrace,-999.000000,138.993631,-999.0,-999.000000,-999.00
Woodhaven,-999.000000,-999.000000,-999.0,67.170455,-999.00
Woodlawn,60.090909,-999.000000,-999.0,-999.000000,-999.00
Woodrow,-999.000000,-999.000000,-999.0,-999.000000,700.00
Woodside,-999.000000,-999.000000,-999.0,85.097872,-999.00

데이터중 neighbourhood_group 값이 Queens값을 가지는 데이터들 중 neighbourhood 그룹별로 price값의 평균, 분산, 최대, 최소값을 구하라

In [204]:
ans = df[df['neighbourhood_group']=='Queens'].groupby('neighbourhood').price.agg(['mean','var','max','min'])
ans

                           mean            var    max  min
neighbourhood
Arverne              171.779221   37383.411141   1500   35
Astoria              117.187778  122428.811196  10000   25
Bay Terrace          142.000000    6816.400000    258   32
Bayside              157.948718  166106.470985   2600   30
Bayswater             87.470588    2330.889706    230   45
Belle Harbor         171.500000    8226.571429    350   85
Bellerose             99.357143    3093.016484    240   42
Breezy Point         213.333333    1008.333333    250  195
Briarwood            105.875000   18503.165909   1000   30
Cambria Heights       81.730769    2960.604615    250   31
College Point         88.000000    6445.555556    400   44
Corona                59.171875    2430.557292    359   23
Ditmars Steinway      95.029126    4214.112785    600   22
Douglaston            82.750000    2347.071429    178   40
East Elmhurst         81.183784    4369.487779    700   16
Edgemere              94.727273    4219.418182    200   40
Elmhurst              80.459916    3896.563005    443   15
Far Rockaway         165.862069   52575.980296    900   35
Flushing              93.514085   12417.177448   1500   15
Forest Hills         121.625000   44533.368881   2350   16
Fresh Meadows         99.500000    6394.451613    375   39
Glendale              90.796296    3230.882250    299   25
Hollis                88.642857    1483.016484    175   50
Holliswood           135.750000    5091.583333    239   79
Howard Beach         115.400000    4241.936842    250   40
Jackson Heights       80.897849    2150.470590    260   23
Jamaica               95.770563    8067.047130   1000   10
Jamaica Estates      182.947368   29006.052632    750   35
Jamaica Hills        132.125000   11304.696429    325   50
Kew Gardens           88.375000    2632.306452    219   35
Kew Gardens Hills    112.307692    6230.621538    399   40
Laurelton             95.333333    4355.529412    254   34
Little Neck           75.200000    2368.700000    149   32
Long Island City     127.465549   15529.503009   2000   30
Maspeth               83.645455    2223.607089    245   11
Middle Village       109.580645    3537.118280    265   28
Neponsit             274.666667    5625.333333    350  200
Ozone Park            85.274194    1705.415389    200   25
Queens Village        83.933333    2386.470056    320   25
Rego Park             83.877358    3659.003863    300   21
Richmond Hill         87.117021    3474.147449    300   28
Ridgewood             77.184397    2629.311889    375   20
Rockaway Beach       132.178571    6254.622078    545   49
Rosedale              76.694915    2963.939801    350   22
South Ozone Park      82.400000    4619.989744    400   29
Springfield Gardens   94.235294    2490.848739    300   40
St. Albans           100.828947    9489.903684    600   25
Sunnyside             84.865014    2727.746922    600   12
Whitestone           107.545455   13632.072727    400   35
Woodhaven             67.170455    1642.464864    250   10
Woodside              85.097872    5001.900636    500   28

데이터중 neighbourhood_group 값에 따른 room_type 컬럼의 숫자를 구하고 neighbourhood_group 값을 기준으로 각 값의 비율을 구하여라

In [219]:
ans = df[['neighbourhood_group','room_type']].groupby(['neighbourhood_group','room_type']).size().unstack()
ans = ans.astype(float)
ans.loc[:,:] = (ans.values / ans.sum(axis=1).values.reshape(-1,1))
print(ans)

room_type            Entire home/apt  Private room  Shared room
neighbourhood_group
Bronx                       0.347388      0.597617     0.054995
Brooklyn                    0.475478      0.503979     0.020543
Manhattan                   0.609344      0.368496     0.022160
Queens                      0.369926      0.595129     0.034945
Staten Island               0.471850      0.504021     0.024129

In [228]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv')
df

,Unnamed: 0,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt
0,0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144
1,1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291
2,2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887
3,3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171
4,4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476
10123,10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764
10124,10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291
10125,10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395
10126,10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294

In [224]:
df.shape

(10127, 19)

In [225]:
df['Income_Category']

0           $60K - $80K
1        Less than $40K
2          $80K - $120K
3        Less than $40K
4           $60K - $80K
              ...
10122       $40K - $60K
10123       $40K - $60K
10124    Less than $40K
10125       $40K - $60K
10126    Less than $40K
Name: Income_Category, Length: 10127, dtype: object

Income_Category의 카테고리를 apply 함수를 이용하여 다음과 같이 변경하여 newIncome 컬럼에 매핑하라 Unknown : N
Less than $40K : a
$40K - $60K : b
$60K - $80K : c
$80K - $120K : d
$120K +’ : e

In [227]:
def change(x):
    if x =='Unknown':
        return 'N'
    elif x =='Less than $40K':
        return 'a'
    elif x =='$40K - $60K':
        return 'b'
    elif x =='$60K - $80K':
        return 'c'
    elif x =='$80K - $120K':
        return 'd'
    elif x =='$120K +' :
        return 'e'

df['newIncome'] = df['Income_Category'].apply(change)
df['newIncome']

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

Map방식 변

In [229]:
dic = {
    'Unknown'        : 'N',
    'Less than $40K' : 'a',
    '$40K - $60K'    : 'b',
    '$60K - $80K'    : 'c',
    '$80K - $120K'   : 'd',
    '$120K +'        : 'e'
}

df['newIncome'] = df['Income_Category'].map(lambda x:dic[x])
df['newIncome']

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

Customer_Age의 값을 이용하여 나이 구간을 AgeState 컬럼으로 정의하라. (0~9 : 0 , 10~19 :10 , 20~29 :20 … 각 구간의 빈도수를 출력하라

In [234]:
def convert(x):
  if x<10:
    return 0
  elif x<19:
    return 10
  elif x<29:
    return 20
  elif x<39:
    return 30
  elif x<49:
    return 40
  elif x<59:
    return 50
  elif x<69:
    return 60
  elif x<79:
    return 70

In [239]:
df['AgeState'] = df['Customer_Age'].apply(convert)
df['AgeState'].value_counts().sort_index()

AgeState
20     139
30    1564
40    4399
50    3336
60     687
70       2
Name: count, dtype: int64

Education_Level의 값중 Graduate단어가 포함되는 값은 1 그렇지 않은 경우에는 0으로 변경하여 newEduLevel 컬럼을 정의하고 빈도수를 출력하라

In [245]:
df['newEduLevel']=df['Education_Level'].map(lambda x: 1 if 'Graduate' in x else 0 )
df['newEduLevel'].value_counts()

newEduLevel
0    6483
1    3644
Name: count, dtype: int64

Credit_Limit 컬럼값이 4500 이상인 경우 1 그외의 경우에는 모두 0으로 하는 newLimit 정의하라. newLimit 각 값들의 빈도수를 출력하라

In [247]:
df['newLimit']=df['Credit_Limit'].map(lambda x : 1 if x>=4500 else 0)
df['newLimit'].value_counts()

newLimit
1    5096
0    5031
Name: count, dtype: int64

Marital_Status 컬럼값이 Married 이고 Card_Category 컬럼의 값이 Platinum인 경우 1 그외의 경우에는 모두 0으로 하는 newState컬럼을 정의하라. newState의 각 값들의 빈도수를 출력하라

In [250]:
df['Marital_Status']

0         Married
1          Single
2         Married
3         Unknown
4         Married
           ...
10122      Single
10123    Divorced
10124     Married
10125     Unknown
10126     Married
Name: Marital_Status, Length: 10127, dtype: object

In [255]:
def convert(x):
  if x.Marital_Status=='Married' and x['Card_Category']=='Platinum' :
    return 1
  else:
    return 0

df['newState']= df.apply(convert,axis=1)
df['newState'].value_counts()

newState
0    10120
1        7
Name: count, dtype: int64

Gender 컬럼값 M인 경우 male F인 경우 female로 값을 변경하여 Gender 컬럼에 새롭게 정의하라. 각 value의 빈도를 출력하라

In [263]:
df['Gender'] = df['Gender'].map({'M':'male','F':'female'})
df['Gender'].value_counts()

Gender
female    5358
male      4769
Name: count, dtype: int64

데이터를 로드하고 각 열의 데이터 타입을 파악하라

In [303]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv')
df

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [304]:
df['Yr_Mo_Dy'] = pd.to_datetime(df['Yr_Mo_Dy'])
df['Yr_Mo_Dy']

0      2061-01-01
1      2061-01-02
2      2061-01-03
3      2061-01-04
4      2061-01-05
          ...
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

Yr_Mo_Dy에 존재하는 년도의 유일값을 모두 출력하라

In [273]:
df['Yr_Mo_Dy'].dt.year.unique()

array([2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978], dtype=int32)

Yr_Mo_Dy에 년도가 2061년 이상의 경우에는 모두 잘못된 데이터이다. 해당경우의 값은 100을 빼서 새롭게 날짜를 Yr_Mo_Dy 컬럼에 정의하라

In [305]:
def fix_year(x):
  import datetime

  year = x.year - 100 if x.year >= 2061 else x.year
  return pd.to_datetime(datetime.date(year,x.month,x.day))
df.Yr_Mo_Dy = df.Yr_Mo_Dy.apply(fix_year)
df.Yr_Mo_Dy

0      1961-01-01
1      1961-01-02
2      1961-01-03
3      1961-01-04
4      1961-01-05
          ...
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

년도별 각컬럼의 평균값을 구하여라

In [310]:
ans = df.groupby(df['Yr_Mo_Dy'].dt.year).mean()
ans

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,,
1961,1961-07-02 00:00:00,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,1962-07-02 00:00:00,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,1963-07-02 00:00:00,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,1964-07-01 12:00:00,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,1965-07-02 00:00:00,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,1966-07-02 00:00:00,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,1967-07-02 00:00:00,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,1968-07-01 12:00:00,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,1969-07-02 00:00:00,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,1970-07-02 00:00:00,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,1971-07-02 00:00:00,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,1972-07-01 12:00:00,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,1973-07-02 00:00:00,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,1974-07-02 00:00:00,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,1975-07-02 00:00:00,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,1976-07-01 12:00:00,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,1977-07-02 00:00:00,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,1978-07-02 00:00:00,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

weekday컬럼을 만들고 요일별로 매핑하라 ( 월요일: 0 ~ 일요일 :6)

In [315]:
df['weekday']=df['Yr_Mo_Dy'].dt.day_of_week

In [318]:
def weekend(x):
  if x>4:
    return 1
  else:
    return 0

df['WeekCheck'] = df['weekday'].apply(weekend)
df['WeekCheck']

0       1
1       0
2       0
3       0
4       0
       ..
6569    0
6570    0
6571    0
6572    1
6573    1
Name: WeekCheck, Length: 6574, dtype: int64

년도, 일자 상관없이 모든 컬럼의 각 달의 평균을 구하여라

In [319]:
df.groupby(df['Yr_Mo_Dy'].dt.month).mean()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday,WeekCheck
Yr_Mo_Dy,,,,,,,,,,,,,,,
1,1969-07-17 06:40:00.000000000,14.847325,12.914560,13.299624,7.199498,11.667734,8.054839,11.819355,9.512047,9.543208,10.053566,14.550520,18.028763,2.989247,0.284946
2,1969-08-17 07:50:33.070866142,13.710906,12.111122,12.879132,6.942411,11.551772,7.633858,11.206024,9.341437,9.313169,9.518051,13.728898,17.156142,3.005906,0.287402
3,1969-09-14 12:00:00.000000000,13.158687,11.505842,12.648118,7.265907,11.554516,7.959409,11.310179,9.635896,9.700324,10.096953,13.810609,16.909317,3.000000,0.283154
4,1969-10-15 00:00:00.000000000,12.555648,10.429759,12.204815,6.898037,10.677667,7.441389,10.221315,8.909056,8.930870,9.158019,12.664759,14.937611,3.011111,0.288889
5,1969-11-14 12:00:00.000000000,11.724032,10.145619,11.550394,6.307487,10.224301,6.942061,8.797738,8.452903,8.040806,8.524857,12.767258,13.736039,2.982079,0.283154
6,1969-12-15 00:00:00.000000000,10.451317,8.949704,10.361315,5.652278,9.529926,6.410093,8.009556,7.920796,7.639796,7.729185,12.246407,12.861818,3.007407,0.285185
7,1970-01-14 12:00:00.000000000,9.992007,8.357778,9.349642,5.416935,9.302634,5.972348,7.843501,7.262760,7.544480,7.321416,11.676505,12.800789,3.001792,0.288530
8,1970-02-14 12:00:00.000000000,10.213411,8.415143,9.993441,5.270681,8.901559,5.891057,7.772312,6.842025,7.240573,7.002783,11.110090,12.565943,2.991039,0.283154
9,1970-03-17 00:00:00.000000000,11.458519,9.981002,10.756883,5.615176,9.766315,6.566222,8.609722,7.745677,7.610556,7.689278,12.686389,14.761963,3.009259,0.287037
10,1970-04-16 12:00:00.000000000,12.660610,11.010681,11.453943,6.065215,10.550251,7.159910,9.387778,8.726308,8.347181,8.850376,14.155323,16.697151,2.998208,0.286738
11,1970-05-17 00:00:00.000000000,13.200722,11.639500,12.293407,6.247611,10.501130,7.134333,10.814861,8.427167,8.604000,8.943167,13.815741,18.114185,2.992593,0.283333
12,1970-06-16 12:00:00.000000000,14.446398,12.353602,13.212276,6.829910,11.301254,7.963710,11.849050,9.209355,9.447258,9.627670,14.259516,18.697599,3.017921,0.288530

모든 결측치는 컬럼기준 직전의 값으로 대체하고 첫번째 행에 결측치가 있을경우 뒤에있는 값으로 대채하라

In [322]:

df = df.fillna(method='ffill').fillna(method='bfill')
df.isnull().sum()

Yr_Mo_Dy     0
RPT          6
VAL          3
ROS          2
KIL          5
SHA          2
BIR          0
DUB          3
CLA          2
MUL          3
CLO          1
BEL          0
MAL          4
weekday      0
WeekCheck    0
dtype: int64

년도 - 월을 기준으로 모든 컬럼의 평균값을 구하여라

In [325]:
df.groupby(df['Yr_Mo_Dy'].dt.to_period('M')).mean()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday,WeekCheck
Yr_Mo_Dy,,,,,,,,,,,,,,,
1961-01,1961-01-16 00:00:00,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226,2.935484,0.290323
1961-02,1961-02-14 12:00:00,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786,3.000000,0.285714
1961-03,1961-03-16 00:00:00,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000,3.000000,0.258065
1961-04,1961-04-15 12:00:00,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333,3.166667,0.333333
1961-05,1961-05-16 00:00:00,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613,2.806452,0.258065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,1978-08-16 00:00:00,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194,2.903226,0.258065
1978-09,1978-09-15 12:00:00,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333,3.100000,0.300000
1978-10,1978-10-16 00:00:00,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000,2.935484,0.290323
1978-11,1978-11-15 12:00:00,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000,2.966667,0.266667
1978-12,1978-12-16 00:00:00,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613,3.193548,0.322581

RPT 컬럼의 값을 일자별 기준으로 1차차분하라

In [326]:
df['RPT'].diff()

0        NaN
1      -0.33
2       3.79
3      -7.92
4       2.75
        ...
6569    3.75
6570   -4.37
6571    0.79
6572    4.50
6573    1.83
Name: RPT, Length: 6574, dtype: float64

RPT와 VAL의 컬럼을 일주일 간격으로 각각 이동평균한값을 구하여라

In [327]:
df[['RPT','VAL']].rolling(7).mean()

            RPT        VAL
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
6569  11.868571   9.362857
6570  11.904286   9.595714
6571  13.017143  10.011429
6572  13.285714  10.118571
6573  14.951429  11.801429

[6574 rows x 2 columns]

In [411]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/seoul_pm.csv')

년-월-일:시 컬럼을 pandas에서 인식할 수 있는 datetime 형태로 변경하라. 서울시의 제공데이터의 경우 0시가 24시로 표현된다

In [355]:
# 24시 -> 00시 + 하루 추가
df['(년-월-일:시)']
df.rename(columns= {'(년-월-일:시)':'date'})

,date,PM10등급,PM10,PM2.5등급,PM2.5,오존등급,오존,이산화질소등급,이산화질소,일산화탄소등급,일산화탄소,아황산가스등급,아황산가스
0,2021-05-15:15,보통,47.0,보통,19.0,좋음,0.017,좋음,0.023,좋음,0.4,좋음,0.003
1,2021-05-15:14,보통,43.0,보통,20.0,좋음,0.024,좋음,0.019,좋음,0.3,좋음,0.003
2,2021-05-15:13,보통,34.0,보통,24.0,보통,0.035,좋음,0.017,좋음,0.4,좋음,0.004
3,2021-05-15:12,보통,41.0,보통,27.0,보통,0.037,좋음,0.020,좋음,0.4,좋음,0.004
4,2021-05-15:11,보통,51.0,보통,34.0,보통,0.033,좋음,0.023,좋음,0.4,좋음,0.005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234,2021-03-25:05,보통,39.0,보통,18.0,좋음,0.026,좋음,0.025,좋음,0.4,좋음,0.003
1235,2021-03-25:04,보통,34.0,좋음,15.0,좋음,0.017,보통,0.033,좋음,0.4,좋음,0.002
1236,2021-03-25:03,보통,35.0,좋음,13.0,좋음,0.029,좋음,0.025,좋음,0.4,좋음,0.003
1237,2021-03-25:02,보통,35.0,좋음,13.0,보통,0.031,좋음,0.025,좋음,0.3,좋음,0.003
1238,2021-03-25:01,보통,42.0,좋음,13.0,좋음,0.022,보통,0.037,좋음,0.4,좋음,0.003

In [414]:
def change(x):
  import datetime
  hour = x.split(":")[1]
  date = x.split(":")[0]

  if hour == '24':
    hour = '00:00:00'

    FinalDate = pd.to_datetime(date+" "+hour) + datetime.timedelta(days=1)

  else:
    hour = hour +':00:00'
    FinalDate = pd.to_datetime(date+" "+hour)

  return FinalDate

df['(년-월-일:시)'] = df['(년-월-일:시)'].apply(change)
df['(년-월-일:시)']

0      2021-05-15 15:00:00
1      2021-05-15 14:00:00
2      2021-05-15 13:00:00
3      2021-05-15 12:00:00
4      2021-05-15 11:00:00
               ...
1234   2021-03-25 05:00:00
1235   2021-03-25 04:00:00
1236   2021-03-25 03:00:00
1237   2021-03-25 02:00:00
1238   2021-03-25 01:00:00
Name: (년-월-일:시), Length: 1239, dtype: datetime64[ns]

일자별 영어요일 이름을 dayName 컬럼에 저장하라

In [415]:
df = df.rename(columns={'(년-월-일:시)':"date"})

In [369]:
df['dayName']= df['date'].dt.day_name()
df['dayName']

0       Saturday
1       Saturday
2       Saturday
3       Saturday
4       Saturday
          ...
1234    Thursday
1235    Thursday
1236    Thursday
1237    Thursday
1238    Thursday
Name: dayName, Length: 1239, dtype: object

일자별 각 PM10등급의 빈도수를 파악하라

In [381]:
ans = df.groupby(df['dayName'],as_index=False).PM10등급
ans.value_counts()

      dayName PM10등급  count
0      Friday     보통    120
1      Friday     나쁨     31
2      Friday     좋음     21
3      Friday   매우나쁨     17
4      Monday     보통     83
5      Monday     좋음     63
6      Monday   매우나쁨     21
7      Monday     나쁨      1
8    Saturday     보통     71
9    Saturday     좋음     54
10   Saturday     나쁨     31
11   Saturday   매우나쁨     27
12     Sunday     좋음     98
13     Sunday     보통     67
14     Sunday     나쁨      2
15     Sunday   매우나쁨      1
16   Thursday     보통    144
17   Thursday     나쁨     41
18   Thursday     좋음      5
19    Tuesday     좋음     74
20    Tuesday     보통     71
21    Tuesday     나쁨     13
22    Tuesday   매우나쁨     10
23  Wednesday     보통     95
24  Wednesday     좋음     46
25  Wednesday     나쁨     26

시간이 연속적으로 존재하며 결측치가 없는지 확인하라

In [386]:
ans = len(df['date'].diff().unique())

if ans==2:
  result = True
else:
  result = False

result

True

오전 10시와 오후 10시(22시)의 PM10의 평균값을 각각 구하여라

In [397]:
df['hour'] = df['date'].dt.hour

result = df[df['hour'].isin([10,22])].groupby('hour')['PM10'].mean()
result

hour
10    70.384615
22    69.941176
Name: PM10, dtype: float64

데이터를 주단위로 뽑아서 최소,최대 평균, 표준표차를 구하여라

In [422]:
df['date'] = pd.to_datetime(df['date'])
df.set_index('date',inplace=True)
df.resample('W').agg(['min','max','mean','std'])

TypeError: agg function failed [how->min,dtype->object]

In [423]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/under5MortalityRate.csv')

Indicator을 삭제하고 First Tooltip 컬럼에서 신뢰구간에 해당하는 표현을 지워라

In [426]:
df.drop('Indicator',axis=1)
df['First Tooltip']  = df['First Tooltip'].map(lambda x:float(x.split("[")[0]))

In [427]:
df

,Location,Period,Indicator,Dim1,First Tooltip
0,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Both sexes,60.27
1,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Male,63.83
2,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Female,56.57
3,Afghanistan,2018,Under-five mortality rate (probability of dyin...,Both sexes,62.54
4,Afghanistan,2018,Under-five mortality rate (probability of dyin...,Male,66.08
...,...,...,...,...,...
29994,Timor-Leste,2002,Under-five mortality rate (probability of dyin...,Both sexes,96.97
29995,Timor-Leste,2002,Under-five mortality rate (probability of dyin...,Male,102.60
29996,Timor-Leste,2002,Under-five mortality rate (probability of dyin...,Female,91.04
29997,Timor-Leste,2001,Under-five mortality rate (probability of dyin...,Both sexes,102.50
29998,Timor-Leste,2001,Under-five mortality rate (probability of dyin...,Male,108.20

년도가 2015년 이상, Dim1이 Both sexes인 케이스만 추출하라

In [435]:
target = df[(df.Period >=2015) & (df.Dim1 =='Both sexes')]
target

,Location,Period,Indicator,Dim1,First Tooltip
0,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Both sexes,60.27
3,Afghanistan,2018,Under-five mortality rate (probability of dyin...,Both sexes,62.54
6,Afghanistan,2017,Under-five mortality rate (probability of dyin...,Both sexes,64.94
9,Afghanistan,2016,Under-five mortality rate (probability of dyin...,Both sexes,67.57
12,Afghanistan,2015,Under-five mortality rate (probability of dyin...,Both sexes,70.44
...,...,...,...,...,...
29943,Timor-Leste,2019,Under-five mortality rate (probability of dyin...,Both sexes,44.22
29946,Timor-Leste,2018,Under-five mortality rate (probability of dyin...,Both sexes,45.62
29949,Timor-Leste,2017,Under-five mortality rate (probability of dyin...,Both sexes,47.27
29952,Timor-Leste,2016,Under-five mortality rate (probability of dyin...,Both sexes,49.01
29955,Timor-Leste,2015,Under-five mortality rate (probability of dyin...,Both sexes,50.76

84번 문제에서 추출한 데이터로 아래와 같이 나라에 따른 년도별 사망률을 데이터 프레임화 하라

In [440]:
target.groupby(['Location','Period'])['First Tooltip'].mean().unstack()

Period                                      2015   2016   2017   2018   2019
Location
Afghanistan                                70.44  67.57  64.94  62.54  60.27
Albania                                     9.57   9.42   9.42   9.53   9.68
Algeria                                    25.18  24.79  24.32  23.81  23.26
Andorra                                     3.53   3.37   3.22   3.09   2.97
Angola                                     88.20  84.21  80.62  77.67  74.69
...                                          ...    ...    ...    ...    ...
Syrian Arab Republic                       23.18  23.27  22.97  22.11  21.53
Tajikistan                                 37.75  36.82  35.81  34.80  33.78
Thailand                                   10.80  10.32   9.86   9.42   9.01
The former Yugoslav Republic of Macedonia  12.97  11.97   9.94   7.83   6.12
Timor-Leste                                50.76  49.01  47.27  45.62  44.22

[172 rows x 5 columns]

Dim1에 따른 년도별 사망비율의 평균을 구하라

In [446]:
df.groupby(['Dim1','Period'])['First Tooltip'].mean().unstack()

Period,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Dim1,,,,,,,,,,,,,,,,,,,,,
Both sexes,147.700816,155.537544,157.811094,156.147206,154.539857,155.797179,159.241163,156.170114,150.813222,150.574000,...,37.718488,35.573663,34.290988,33.099360,32.053314,31.012093,29.956337,29.030465,28.083837,27.191744
Female,140.909796,149.210175,151.516094,150.250882,148.688286,149.843205,153.048721,149.988295,144.719667,144.451474,...,34.953023,32.877616,31.654070,30.521337,29.524302,28.544360,27.542035,26.675291,25.782616,24.945349
Male,154.151224,161.538246,163.760781,161.742059,160.081000,161.456923,165.089535,162.015000,156.573556,156.375053,...,40.340174,38.140291,36.793081,35.543663,34.446105,33.354302,32.242616,31.273198,30.283023,29.350349

데이터에서 한국 KOR 데이터만 추출하라

In [449]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/winter.csv')
df.head(3)

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1924,Chamonix,Biathlon,Biathlon,"BERTHET, G.",FRA,Men,Military Patrol,Bronze
1,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, C.",FRA,Men,Military Patrol,Bronze
2,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, Maurice",FRA,Men,Military Patrol,Bronze

In [452]:
kor=df.loc[df['Country']=='KOR']

한국 올림픽 메달리스트 데이터에서 년도에 따른 medal 갯수를 데이터프레임화 하라

In [459]:
kor.groupby(['Year','Medal']).size().unstack()

Medal  Bronze  Gold  Silver
Year
1992      1.0   5.0     1.0
1994      1.0   8.0     1.0
1998      2.0   6.0     4.0
2002      NaN   5.0     2.0
2006      2.0  14.0     3.0
2010      2.0   6.0    10.0
2014      2.0   7.0     5.0

전체 데이터에서 sport종류에 따른 성별수를 구하여라

In [461]:
df.groupby(['Sport','Gender']).size().unstack()

Gender       Men  Women
Sport
Biathlon     270    150
Bobsleigh    416     36
Curling       97     75
Ice Hockey  1231    305
Luge         135     45
Skating      665    564
Skiing      1130    651

전체 데이터에서 Discipline종류에 따른 따른 Medal수를 구하여라

In [463]:
df.groupby(['Discipline','Medal']).size().unstack()

Medal                      Bronze  Gold  Silver
Discipline
Alpine Skiing                 141   143     144
Biathlon                      139   140     141
Bobsleigh                     147   134     141
Cross Country Skiing          263   264     262
Curling                        56    58      58
Figure skating                118   122     119
Freestyle Skiing               34    34      34
Ice Hockey                    512   510     514
Luge                           60    62      58
Nordic Combined                55    55      55
Short Track Speed Skating      96    97      97
Skeleton                       10    10      10
Ski Jumping                    68    69      70
Snowboard                      30    30      30
Speed skating                 190   193     197

In [464]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/mergeTEst.csv',index_col= 0)
df.head(3)

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Afghanistan,64.023,61.640,59.367,57.170,55.08,53.107,51.267,49.560,47.983,46.453
Albania,11.803,10.807,9.943,9.267,8.79,8.493,8.363,8.363,8.453,8.597
Algeria,23.540,22.907,22.450,22.117,21.85,21.587,21.257,20.850,20.407,19.930

In [465]:
df1 = df.iloc[:4,:]
df2 = df.iloc[4:,:]

display(df1)
display(df2)

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Afghanistan,64.023,61.640,59.367,57.170,55.08,53.107,51.267,49.560,47.983,46.453
Albania,11.803,10.807,9.943,9.267,8.79,8.493,8.363,8.363,8.453,8.597
Algeria,23.540,22.907,22.450,22.117,21.85,21.587,21.257,20.850,20.407,19.930
Andorra,4.240,4.033,3.843,3.667,3.49,3.330,3.187,3.060,2.933,2.827

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Angola,75.713,71.280,67.233,63.570,60.430,57.757,55.510,53.460,51.757,50.093
Antigua and Barbuda,8.667,8.223,7.807,7.420,7.070,6.757,6.483,6.230,6.000,5.783
Argentina,12.887,12.380,11.840,11.283,10.733,10.203,9.683,9.177,8.680,8.227
Armenia,16.497,15.677,14.897,14.170,13.477,12.817,12.183,11.583,11.007,10.497
Australia,3.993,3.803,3.623,3.467,3.343,3.253,3.183,3.137,3.090,3.047
Austria,3.573,3.463,3.333,3.210,3.113,3.043,2.987,2.943,2.897,2.843

In [468]:
df=pd.concat([df1,df2])

In [469]:
df3 = df.iloc[:2,:4]
df4 = df.iloc[5:,3:]

display(df3)
display(df4)

               2010    2011    2012    2013
Location
Afghanistan  64.023  61.640  59.367  57.170
Albania      11.803  10.807   9.943   9.267

                       2013    2014    2015    2016    2017    2018    2019
Location
Antigua and Barbuda   7.420   7.070   6.757   6.483   6.230   6.000   5.783
Argentina            11.283  10.733  10.203   9.683   9.177   8.680   8.227
Armenia              14.170  13.477  12.817  12.183  11.583  11.007  10.497
Australia             3.467   3.343   3.253   3.183   3.137   3.090   3.047
Austria               3.210   3.113   3.043   2.987   2.943   2.897   2.843

In [470]:
pd.concat([df3,df4],join='inner')

                       2013
Location
Afghanistan          57.170
Albania               9.267
Antigua and Barbuda   7.420
Argentina            11.283
Armenia              14.170
Australia             3.467
Austria               3.210